ManageIQ/manageiq-providers-amazon

- .rspec
- .rspec_ci
- Gemfile
- README.md
- spec/spec_helper.rb
@durandom Please review.
Two weird things I noticed locally which may change how we have to run the tests
1.  After `app:test:manageiq-providers-amazon:setup` I see `.I, [2016-06-28T16:38:38.999289 #96868]  INFO -- : Reporting coverage data to Code Climate.`.  This is probably because we run two separate steps.  We might want to try to find a way to make `bundle exec rake` to do the right thing, but that might be tricky.
2. After `app:test:manageiq-providers-amazon` I see `Coverage = 89.35%. Sending report to https://codeclimate.com for branch aws_move_to_gem... done.`  I'm not sure why it's choosing that branch except that that's the branch we use for the "dummy" app.  Once everything is on master, this is fine, but it's still very weird.
I see a bunch of other small, minor, oddities we …
> Add CodeClimate test coverage reporter

- app/models/manageiq/providers/amazon/instance_types.rb
http://aws.amazon.com/ec2/instance-types/ updated, so reflecting the
changes here.
@blomquisg @durandom Please review.  I Think this should be darga/yes (which makes things complicated, so I'll have to review with @chessbyte how to backport if necessary).
> Update x1.32xlarge to enhanced and clustered networking.

- app/models/manageiq/providers/amazon/manager_mixin.rb
because for [verify_credentials](https://github.com/ManageIQ/manageiq-providers-amazon/blob/7dc6a4b72dfe9b2c63ffdf658cd75298e1c49f9a/app/models/manageiq/providers/amazon/manager_mixin.rb#L48) an exception could also occur before raw_connect
Or maybe the execption happend in [VMDB::Util.http_proxy_uri](https://github.com/ManageIQ/manageiq-providers-amazon/blob/7dc6a4b72dfe9b2c63ffdf658cd75298e1c49f9a/app/models/manageiq/providers/amazon/manager_mixin.rb#L73) - thats why I moved it further down
this might have been the reason in this issue https://github.com/ManageIQ/manageiq/issues/9342
@blomquisg review and merge?
> require aws-sdk also in translate_exception

- app/models/manageiq/providers/amazon/cloud_manager.rb
removed hardcoded classes that support provisioning from miq_provision
Managers of providers answer the question wether they support
provisioning via automate or not. The BaseManager does not by default.
related PR https://github.com/ManageIQ/manageiq/pull/8351
> Amazon CloudManager supports provisioning via automate

- app/models/manageiq/providers/amazon/cloud_manager.rb
removes hard wiring of cloudmanagers to discovery page.
related PR: https://github.com/ManageIQ/manageiq/pull/8951
@martinpovolny merge this one too?
> refactor discovery to SupportsFeature style

- Gemfile
- manageiq-providers-amazon.gemspec
Dont duplicate dependencies  but require from manageiq test app
fixes: https://github.com/ManageIQ/manageiq-providers-amazon/issues/1
~~requires: https://github.com/ManageIQ/manageiq/pull/9507~~
requires: https://github.com/ManageIQ/manageiq/pull/9534
> require boot dependencies from manageiq app

- .travis.yml
- lib/tasks/spec.rake
- spec/spec_helper.rb
* removes ENGINE_ROOT to make the specs run from miq
```bash
~/src/manageiq master
❯ bundle exec rails test:providers:amazon
** master - DB vmdb_test on
** master - DB vmdb_test on
Randomized with seed 30066
.................................................................................................................
Finished in 13.21 seconds (files took 5.78 seconds to load)
113 examples, 0 failures
Randomized with seed 30066
```
* renames specs to providers:amazon for clarity
> run all specs under spec/ and not only models

- app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
Purpose or Intent
-----------------
AWS can have secondary private IP address assigned to the ENI,
our current model does not allow that. Probably the best fix is,
to expand unique index of the cloud_subnet_network_ports to
include address. But as a backportable fix, we need to display
only the first one, since we can't backport a migration.
Steps for Testing/QA
-----------------
With this fix, having secondary fixed IP address on ENI will not fail refresh. Only first fixed IP will be visible though.
> Workaround for a secondary fixed IP for ENI

- spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb
fixes warnings. before this would not test the right classes
```
/home/travis/build/ManageIQ/manageiq-providers-amazon/spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb:540: warning: toplevel constant LoadBalancer referenced by ManageIQ::Providers::Amazon::CloudManager::LoadBalancer
```
in https://travis-ci.org/ManageIQ/manageiq-providers-amazon/builds/153278362#L499-L505
> correct classnames

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
it could be that there is an empty string as the name of a vm. This would result in a validation error on `Vm` and failing the whole refresh.
https://bugzilla.redhat.com/show_bug.cgi?id=1353979
* add a name to a instance in aws console
* clear the name and add an empty string as the name in aws console
* wait for the refresh to fail
> check if name is blank and use instance_id instead

- config/initializers/gettext.rb
- locale/ManageIQ_Providers_Amazon.pot
- locale/en/ManageIQ_Providers_Amazon.po
- locale/ja/ManageIQ_Providers_Amazon.po
- locale/zh_CN/ManageIQ_Providers_Amazon.po
Changes:
* added a gettext catalog to the `ManageIQ::Providers::Amazon` provider plugin. The catalog was
generated automatically by invoking the following rake task in the ManageIQ git checkout:
```
rake locale:plugin:find[ManageIQ::Providers::Amazon]
```
* The `ManageIQ::Providers::Amazon` plugin now registers its own catalog with the main ManageIQ
rails app. This way the provider plugin makes the fast_gettext engine aware of the plugin's gettext catalog.
> Add gettext catalog to ManageIQ::Providers::Amazon plugin

- app/models/manageiq/providers/amazon/cloud_manager/provision/configuration.rb
- app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb
In the provisioning workflow, we need to send allocation_id for a floating IP, otherwise the provisioning will fail, when deploying VPC VM
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1373438
Fixes issue:
https://github.com/ManageIQ/manageiq/issues/10586
> Fix vpc floating ips refresh and association

- spec/factories/floating_ip.rb
Moving the floating_ip factory over here.
I'm thinking about creating factories for all STI models that are defined in a provider in a dynamic way.
> move floating ip factory from manageiq

- app/models/manageiq/providers/amazon/manager_mixin.rb
This links to PR [#10368](https://github.com/ManageIQ/manageiq/pull/10368)
Allowing a per provider proxy setting in the Appliance Config.
> Override default proxy from provider

- spec/models/manageiq/providers/amazon/network_manager/floating_ip_spec.rb
- spec/spec_helper.rb
this needs https://github.com/ManageIQ/manageiq/pull/11414 to be merged
future note: I'm thinking of running specs for STI models automatically. So a providers author does not have to include those, but once he inherits from a miq model, then the shared example for that is run.
cc @blomquisg
> Floating ip spec as shared example

- app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
ok, heads up, I tested it and yes, it returns a string. This would work because 
```ruby
"vpc"['vpc'] == 'vpc'
"standard"['vpc'] == nil
```
but thats not really intention revealing :)
so do you mind changing it to
```ruby
cloud_network_only = ip.domain == "vpc" ? true : false
```
from this PR
https://github.com/ManageIQ/manageiq-providers-amazon/pull/43#discussion-diff-78062693
@blomquisg please review and merge
> more intention revealing detection of vpc

- app/models/manageiq/providers/amazon/cloud_manager/template.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm.rb
`supports :migrate` was added in https://github.com/ManageIQ/manageiq/pull/9990
`supports :smartstate_analysis` was added in https://github.com/ManageIQ/manageiq/pull/9865
> remove stale methods that are superseded by supports :feature blocks

- app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
We always need to initialize the top level collection,
otherwise it would not invoke deleting of all listeners in
DB when API returns none.
> We always need to initialize the top level collection

- app/models/manageiq/providers/amazon/regions.rb
see announcement
https://aws.amazon.com/blogs/aws/now-open-aws-us-east-ohio-region/
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1389304
@blomquisg how far do we backport this? do we need a BZ for each backport?
> add us-east-2 ohio region

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser_dto.rb
Fill out guest os correctly, inferring it from the image location
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1393547
> Fill out guest os correctly

- app/models/manageiq/providers/amazon/cloud_manager.rb
otherwise it could happen that one process deletes the manager
and another one saves it and the saving one would add back
a deleted manager.
https://bugzilla.redhat.com/show_bug.cgi?id=1389459
https://bugzilla.redhat.com/show_bug.cgi?id=1393675
https://github.com/ManageIQ/manageiq/pull/12878
https://github.com/ManageIQ/manageiq-providers-azure/pull/13
> Add managers in before_create callback instead of before_validation

- spec/requests/api/provision_requests_spec.rb
This spec is heavily tied to amazon and should move over to the amazon gem.
It was introduced here https://github.com/ManageIQ/manageiq/pull/6388 
PR on miq: https://github.com/ManageIQ/manageiq/pull/12542
commit that removed it: ManageIQ/manageiq@21e617a9c6e6b5849d79fd61b4f86c38c6fdf0d
> move aws api provision spec from manageiq to provider

- app/models/manageiq/providers/amazon/cloud_manager/orchestration_service_option_converter.rb
- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_service_option_converter_spec.rb
Before when creating a Cloudformation stack we only accept two optional options, timeout and on_failure. Feature request https://bugzilla.redhat.com/show_bug.cgi?id=1385712 wants to set the capacities option.
This work now enables manageiq users to supply any option that Cloudformation supports. The conversion is based on the assumption that the options are input through manageiq service dialog. Most of the inputs are through textfields:
- timeout
- role_arn
- policy: the code interprets whether it is an url or policy body
- resource types: comma separated string; converted to an array
- notification arns: comma separated string; converted to an array
- tags: string in the format of `tagKey1 => tagVal1, tagKey2 => tagVal2`; converted to an array of hashes
Others are from dropdown lists:
- …
> Support all options to create orchestration stacks

- app/models/manageiq/providers/amazon/regions.rb
- spec/models/manageiq/providers/amazon/regions_spec.rb
Add additional regions to be specified in settings, corresponding key in `config/settings.yml` added in https://github.com/ManageIQ/manageiq/pull/12965
https://bugzilla.redhat.com/show_bug.cgi?id=1389068
> Allow additional_regions to be specified in settings

- config/settings.yml
I will remove the settings from manageiq/config/settings.yml once this is merged
> moving settings from manageiq

- .travis.yml
- Rakefile
- lib/manageiq-providers-amazon.rb
Following somewhat the setup in https://github.com/ManageIQ/manageiq-content/blob/master/Rakefile
now you can just `bundle exec rake` to run the tests.
I think it's worth keeping the tasks at [lib/tasks/spec.rake](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/lib/tasks/spec.rake) as they can be run within the manageiq app then as well.
I also added a explaining error to `Gemfile` in case `spec/manageiq` is not there
@bdunne @Fryguy wdyt?
If this is good, I'd add that to the provider generator
> make spec the default rake task

- app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb
The AWS_EC2_Instance events have their own automate [events](https://github.com/ManageIQ/manageiq/tree/3921e87915b5a69937b9d4a70bb24ab71b97c165/db/fixtures/ae_datastore/ManageIQ/System/Event/EmsEvent/Amazon.class) connected, which trigger a refresh.
Other Events, such as a creation of an Elastic IP would not trigger a refresh.
On the other hand [ConfigurationItemChangeNotification](https://github.com/ManageIQ/manageiq/blob/3921e87915b5a69937b9d4a70bb24ab71b97c165/db/fixtures/ae_datastore/ManageIQ/System/Event/EmsEvent/Amazon.class/configurationitemchangenotification.yaml) is not used as a event_type.
So I rewrite all events that are _not_ AWS_EC2_Instance_.* to ConfigurationItemChangeNotification in order to trigger a refresh.
Here is a snapshot of what happens, when you setup a new …
> map event unknown to automate to ConfigurationItemChangeNotification

- app/models/manageiq/providers/amazon/inventory.rb
- app/models/manageiq/providers/amazon/inventory/factory.rb
- app/models/manageiq/providers/amazon/inventory/hash_collection.rb
- app/models/manageiq/providers/amazon/inventory/inventory_collection_default_init_data.rb
- app/models/manageiq/providers/amazon/inventory/targets.rb
- app/models/manageiq/providers/amazon/inventory/targets/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/targets/event_payload_vm.rb
- app/models/manageiq/providers/amazon/inventory/targets/network_manager.rb
Inventory abstraction for data fetching and storing in inventory collections
> Inventory abstraction for data fetching and storing in inventory collections

- app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_parser_spec.rb
I guess since the switch to aws-sdk-v2 we are not associating events to vms anymore 😢 
But nobody noticed... What does that mean?
added a test to make sure it does not happen again
@blomquisg euwe ? But there is no BZ for it...
> fix connection of events to ems_ref

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
Fill guest_os correctly, inferring it from Image location
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1393547
Clean cherrypick of https://github.com/ManageIQ/manageiq-providers-amazon/pull/84/commits/8424752f464cb2691775cb457457b2d39c608403
from the PR https://github.com/ManageIQ/manageiq-providers-amazon/pull/84
the other commit of the PR is not relevant
> [EUWE] Fill guest_os correctly

- app/models/manageiq/providers/amazon/block_storage_manager.rb
- app/models/manageiq/providers/amazon/block_storage_manager/cloud_volume.rb
- app/models/manageiq/providers/amazon/block_storage_manager/cloud_volume_snapshot.rb
- app/models/manageiq/providers/amazon/block_storage_manager/refresh_parser.rb
- app/models/manageiq/providers/amazon/block_storage_manager/refresh_parser_inventory_object.rb
- app/models/manageiq/providers/amazon/block_storage_manager/refresh_worker.rb
- app/models/manageiq/providers/amazon/block_storage_manager/refresh_worker/runner.rb
- app/models/manageiq/providers/amazon/block_storage_manager/refresher.rb
- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/factory.rb
- app/models/manageiq/providers/amazon/inventory/inventory_collection_default_init_data.rb
- app/models/manageiq/providers/amazon/inventory/targets/block_storage_manager.rb
- config/settings.yml
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/block_storage_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
This commit sets up the core structure of the new AWS EC2 block storage
manager. It provides just the basic stubs and tests that are to be
extended to allow for complete management of Amazon block storage
The refresher collects data about existing volumes and private
snapshots. Volumes are not yet linked to disks of virtual machines
collected by the cloud manager.
Depends on [Add storage manager mixins](https://github.com/ManageIQ/manageiq/pull/13384) PR from core repo.
> Introduce Amazon Block Storage  Manager (EBS)

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory.rb
- app/models/manageiq/providers/amazon/inventory/factory.rb
- app/models/manageiq/providers/amazon/inventory/inventory_collection_default_init_data.rb
- app/models/manageiq/providers/amazon/inventory/targets/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser_inventory_object.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_worker.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_worker/runner.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresher.rb
- config/settings.yml
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Similarly to #101 this commit sets up the core structure of the new AWS S3 manager. 
It provides just the basic stubs and tests that are to be extended.
The refresher collects data about existing buckets.
> Introduce Amazon S3 StorageManager

- .travis.yml
without an install script travis defaults to bundle install
because there is a Gemfile in the project root.
This effectively runs bundle twice, because we also run it from
bin/setup
> dont run bundle twice on travis

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser_inventory_object.rb
- app/models/manageiq/providers/amazon/inventory/inventory_collection_default_init_data.rb
- app/models/manageiq/providers/amazon/inventory/targets/cloud_manager.rb
- app/models/manageiq/providers/amazon/network_manager/refresh_parser_inventory_object.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_inventory_object.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser_inventory_object.rb
Will be fixing a CI after https://github.com/ManageIQ/manageiq/pull/13565 is merged
This patch brings needed ext_management_system relation to each parsed item and optimizes how we store Relationships and Ancestry
> Changes after inventory refresh memory optimizations

- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_inventory_object.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
This patch adds the ability to identify base snapshot, i.e. the snapshot
that was used to create a specific volume. Both legacy parser and
inventory object parser are updated, along with the spec. The latter
adds tests for specific volume and snapshot to make sure proper values
are identified.
> Add links between cloud volumes and base snapshots

- app/models/manageiq/providers/amazon/inventory/targets/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
- app/models/manageiq/providers/amazon/refresh_helper_methods.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_inventory_object.rb
Refresh parser and inventory object will retrieve the availability zone from the parent manager or inventory and save it into the cloud volume hash.
Depends-On: https://github.com/ManageIQ/manageiq/pull/13654
> Parse availability zone of an EBS volume

- app/models/manageiq/providers/amazon/cloud_manager/refresher.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb
While parsing volumes immediately after new AWS manager is created, EBS
manager failed to get proper links to availability zones, because it was
parsing data in parallel to the cloud manager. This patch queues the EBS
storage manager parse in the same way as the network manager, i.e.
immediately after the cloud inventory is saved, EBS refreshes the data
once more.
@miq-bot assign @Ladas 
@Ladas I assigned you because there is a todo for you and would like to check if this is still valid way to go.
> Queue EBS storage refresh after cloud inventory is saved

- app/models/manageiq/providers/amazon/cloud_manager.rb
It appears we made a mistake while adding eBS and S3 providers adding
the same `has_many :storage_managers` twice. Patch is removing this.
@miq-bot assign @bronaghs
> Remove duplicate for `storage_manager` association

- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_inventory_object.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
Name is defined as a tag and can be optional. Patch uses the id of
the volume/snapshot if name is not given.
> Parse the name of EBS volume or snapshot

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser_inventory_object.rb
- app/models/manageiq/providers/amazon/refresh_helper_methods.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb
Besides collecting ephemeral storage in the AWS cloud manager refresh
parser, we are adding inventory of attached block devices. This is
necessary because with the introduction of the EBS manager we are adding
disks there as well. If the cloud manager does not collect attached
block devices, those disks collected by the EBS manager will be removed
from the inventory.
The suggested change does not require any change in the core repository.
> Collect block device mappings in AWS cloud manager

- app/models/manageiq/providers/amazon/inventory/target/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser_inventory_object.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
This patch currently works only for the legacy refresh parser. It will look for the instance (VM) referenced in the attachment section of the volume data and create a backing link between the volume and instance's disk. Linking is done similar to the OpenStack (Cinder) provider.
Inventory object doesn't work yet as I can't figure out how to properly get the hardware and disks from the corresponding `:vm` inventory object.
Specs will also fail because I am using local VCR with our own account. They are nevertheless provided for inspection.
@miq-bot add_label wip, enhancement
@miq-bot assign @Ladas 
Depends on: #122. The spec will be updated with the data from the VCR received from this PR.
> Link volumes to corresponding VM disks

- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Use match_array for arrays, using eq can cause random spec
failures, because it depends on the order.
> Use match_array for arrays

- app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb
- app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/EC2_Instance_State_change_Notification_pending.json
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/EC2_Instance_State_change_Notification_running.json
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/EC2_Instance_State_change_Notification_stopped.json
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/StartInstances.json
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/StopInstances.json
- spec/models/manageiq/providers/amazon/cloud_manager/event_parser_spec.rb
Amazon event parser for CloudWatch events. The parser is able
to recognize CloudWatch ec2 events and CloudWatch API events
collected via CloudTrail.
> Amazon event parser for CloudWatch events

- app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream_spec.rb
Currently, if the AWS_Config SNS topic does not exist on AWS a warning is written to the aws.log file and events are not collected.
This PR will first try to get the AWS_Config topic, and if it does not exist one will be created.
https://github.com/ManageIQ/manageiq-providers-amazon/issues/126
https://www.pivotaltracker.com/story/show/138951121
> Creates the AWS SNS topic if one isn't already present.

- app/models/manageiq/providers/amazon/inventory/inventory_collection_default_init_data.rb
- app/models/manageiq/providers/amazon/inventory/target.rb
- app/models/manageiq/providers/amazon/inventory/target/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/target/target_collection.rb
Moving to use only kwargs for InventoryCollection init.
Unifying format, preparing for the abstraction of the
InventoryCollection definitions.
Depends on https://github.com/ManageIQ/manageiq/pull/13739
> Moving to use only kwargs for InventoryCollection init

- app/models/manageiq/providers/amazon/cloud_manager/event_catcher/runner.rb
The [```filtered?```](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager/event_catcher/runner.rb#L30..32) event uses the event ```MessageType``` property to determine if an event is on the blacklist of events that should be filtered out. Prior to adding support for CloudWatch events, there was always a MessageType property but that is no longer the case.
The ```filtered?``` method receives the event after it has already been partially parsed and the event name has already been normalized. This allows us to use the event name regardless of the AWS service it came from.
> Filter events using eventType instead of MessageType

- app/models/manageiq/providers/amazon/cloud_manager/vm.rb
- app/models/manageiq/providers/amazon/manager_mixin.rb
since https://github.com/ManageIQ/manageiq/pull/10588 got merged (a long time ago) these methods are no more called anyway - remove cruft
> remove validate_timeline

- app/models/manageiq/providers/amazon/inventory/collector.rb
- app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/manager_mixin.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresher.rb
- config/settings.yml
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Work for Amazon ObjectStorage (S3) provider.
Parsing information about objects on S3 buckets. Calculating bucket's size and object count.
Implemented with both old and inventory parser.
@miq-bot add_label enhancement, euwe/no
> Amazon S3 objects inventoring

- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Disabling a broken spec caused by
https://github.com/ManageIQ/manageiq/pull/14009
> Disabling a broken spec

- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Depends on:
Reenable specs as an issue in core creating zombies was fixed
> Reenable specs as an issue in core creating zombies was fixed

- app/models/manageiq/providers/amazon/builder.rb
- app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
- app/models/manageiq/providers/amazon/inventory/persister.rb
A temporary solution to make Targeted refresh work. We need to figure out a right place to parse all references that relate to a Target and passing them to Colletor and Persister
> Pass collector to persister to make targeted refresh work

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- spec/factories/cloud_volume.rb
- spec/factories/ext_management_system.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
This patch adds support for the following operations on the cloud volume: create new, attach, detach, delete and update name. Stubbed specs are provided for these operations.
@miq-bot assign @blomquisg
> Cloud volume operations

- app/models/manageiq/providers/amazon/cloud_manager.rb
- config/settings.yml
There is currently no way to filter out events using a configuration setting. There already is a blacklisted_events table but the only way to populate it is through hard coding event names in the provider cloud manager or to create rows through the rails console.
This PR creates a configuration setting for Amazon in the config/settings.yml file where event names to be filtered out can be added.
This change can be applied to each provider individually.
https://www.pivotaltracker.com/story/show/139861047
https://github.com/ManageIQ/manageiq-providers-amazon/issues/140
> Filter out events in Settings instead of CloudManager

- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
Amazon EBS refresh parser is using an inexistent logger (`_log`) resulting in errors due to a missing symbol. Patch fixes this by using the AWS-specific logger.
Thanks @miha-plesko for this find!
@Ladas would you be willing to review this one?
> Fix logger in Amazon EBS refresh parser

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb
- spec/factories/cloud_volume_snapshot.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot_spec.rb
Create and delete snapshot operations are added to the cloud volume snapshot. Queued versions of these operations are provided allowing background creation and deletion of volume snapshots.
This currently depends on #151 adding cloud volumes support as it extends the cloud volume with the operation to create a new snapshot from the volume.
@miq-bot assign @durandom
> Add cloud volume snapshot operations for EBS manager

- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser.rb
- spec/factories/cloud_object_store.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
CloudObjectStoreContainer now supports async task processing
therefore we support the first operation with this commit: destroy.
See video attached to the manage-ui-classic PR (link below).
Links:
* https://github.com/ManageIQ/manageiq/pull/13965 (already merged)
* https://github.com/ManageIQ/manageiq-ui-classic/pull/420 (GUI for this operation)
@miq-bot assign @blomquisg
> Support deletion of CloudObjectStoreContainer

- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_object.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Support deletion of CloudObjectStoreObject for Amazon provider.
Depends on (from other repos):
* https://github.com/ManageIQ/manageiq/pull/14080 (merged)
* https://github.com/ManageIQ/manageiq/pull/14189 (must be merged in one take with this PR) 👈 ‼️ 
Will enable merge of:
* https://github.com/ManageIQ/manageiq-ui-classic/pull/497
> Support deletion of CloudObjectStoreObject

- app/models/manageiq/providers/amazon/cloud_manager/vm/operations/guest.rb
Sets the same power state `shutting_down` when rebooting an instance as in the [stop operation](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager/vm/operations/power.rb#L20)
`pending` is basically an intermediate state ([aws api](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceState.html)) - which we translate to [suspended](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager/vm.rb#L10). But we want to show it in the UI as `shutting down`
In case the operation was not carried out correct via aws, then the next refresh will set it to the real state.
@mkanoor I'm not sure if this has an impact on automate. See this PR …
> set power state to shutting_down when rebooting an instance

- app/models/manageiq/providers/amazon/storage_manager/s3.rb
As reported in https://github.com/ManageIQ/manageiq-providers-amazon/issues/161, calling
```ruby
ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer.name
```
in refresh parser resulted in warning "warning: toplevel constant CloudObjectStoreContainer referenced by ManageIQ::Providers::Amazon::StorageManager::S3::CloudObjectStoreContainer" being printed to evm.log. Fixing this by hard-coding `type` name as string. Other refresh parsers have it hard-coded as well, but I wanted to be smarter... :D
> Suppress warning "toplevel constant referenced"

- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
When user adds AWS cloud manager S3 storage manager is added as well and refresh is triggered for it. However, during this first refresh, CloudObjectStoreContainers and CloudObjectStoreObjects were assigned empty type. This prevented S3 storage manager from showing them as its children. When user triggered refresh on S3 manually, S3 manager assumed that no object is in database yet resulting in every object
being fetched once again while keeping orphaned ones in database. And again. And again... The database was getting bigger and bigger with every new refresh.
Fixed with this commit - turns out we have to specify default class for Containers and Objects and the orphaned database entries wont appear.
> Set default Container and Object class when collecting inventory for the 1st time

- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
With this commit we implement raw method that clears bucket on the S3. We also render it supported so that GUI will display button. To `clear` bucket means to remove all objects within it.
Depends on (from other repos):
* https://github.com/ManageIQ/manageiq/pull/14082 (merged)
> Support operation "clear" on CloudObjectStoreContainer

- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
For buckets in US East (N. Virginia) region, the SDK returns empty string "" instead of "us-east-1". But when connecting to S3, we need to specify "us-east-1" explicitly. With this commit we map empty string to region name to prevent error.
@miq-bot assign @Ladas 
> AWS SDK call `get_bucket_location` returns empty string

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
This patch implements a method from the base cloud volume that provides
the list of VMs (instances) that the volume can be attached to. In case
of Amazon, the volume can be attached to any instance residing in the
same availability zone as the volume itself.
Depends on: ManageIQ/manageiq#14058
@miq-bot add_label enhancement,pending core
> List VMs from the same availability zone as volume

- app/models/manageiq/providers/amazon/network_manager/event_catcher.rb
- app/models/manageiq/providers/amazon/network_manager/metrics_collector_worker.rb
Purpose
-------
Avoid issues in development mode when eager loading, since this doesn't work.
Background
----------
As part of https://github.com/ManageIQ/manageiq/pull/14261 I am trying to get `eager_loading` fuctioning properly with `manageiq`.  When doing eager loading in development mode, things bust because `require_nested` on these two models is invalid because there isn't a corresponding nested directory available for these two models.
Not sure the status of these models, because they aren't included in the main `NetworkManager` in this provider, so they might be incomplete or not used.  Only eager loading without cached classes seems to cause this error to, so I will let the reviewer be the judge of whether this fix is sufficient, or we should consider removing these models …
> Remove `require_nested :Runner` from NetworkManager::EventCatcher and NetworkManager::MetricsCollectorWorker

- config/settings.yml
timelines have been enabled for aws for a long time
and we have been collecting events for some time.
We just did not display any events by default.
Display those 6 EC2 events because we already have them
in [automate](https://github.com/ManageIQ/manageiq-content/tree/6be7ec14216da302f9fc3f805670c8ac340211e4/content/automate/ManageIQ/System/Event/EmsEvent/Amazon.class) triggering a refresh
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1392391
since https://github.com/ManageIQ/manageiq/pull/13942 has been merged, I can add those events here 😋 
@blomquisg @bronaghs please review
> add amazon events to settings to display them in timelines

- app/models/manageiq/providers/amazon/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
Support operation `create` for CloudObjectStoreContainer
Depends on:
* https://github.com/ManageIQ/manageiq/pull/14269 (merged)
@miq-bot assign @bronaghs
> Support operation `create` for CloudObjectStoreContainer

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/persister/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb
This PR parses AWS Tags which are saved in the database as custom attributes.
Currently AWS only supports tagging VMs and Images.
This PR takes care of the parsing and depends on the model and post processing logic getting merged first:
https://github.com/ManageIQ/manageiq/pull/14202 (Status: merged)
A UI PR will be made separately to display the custom attributes in the Labels table of the VMs and Images.
Steps to test:
1. Add tags to a VM or image through the AWS console.
2. Add an AWS provider to the MIQ UI
3. Open the Summary page for the VM selected in 1) and make sure a "Labels" table exists and displays the tags configured in 1)
https://www.pivotaltracker.com/story/show/139414085
> Gather AWS labels and create CustomAttributes

- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Relative path for the VCRs is allowing to run specs from the core
> Relative path for the VCRs is allowing to run specs from the core

- manageiq-providers-amazon.gemspec
In order to enable updating EBS volumes on the fly, the SDK needs to support the [#modify_volume](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#modify_volume-instance_method). This has been introduced in version [2.7.8](https://github.com/aws/aws-sdk-ruby/commit/9e0558fdfb0eec9ed03f500d552edd3b36cdaa9f#diff-be5c280d1f1bc5bd07cf35078448e1caR1668) of aws-sdk gem.
This patch thus increases the minimum supported version to v2.7.8.
> Increase minimum AWS version for modify_volume

- app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
If VM was scheduled for refresh, always refresh the references that
we can obtain by scanning the Vm in the API and our DB. This way, we
should always get a Vm that has all references filled.
The alternative for this would be a multi-phase refresh, where each
refresh can be planning another refresh for missing references.
In this case, we output a fully refreshed Vms in one step, which
will be later configurable, as this is handy for integration
with external tools. E.g. when we need to send refreshed data
to ansible, we need Vm completely refreshed after 1 refresh, not
possible many incremental refreshes.
> Do vm targeted full refresh by default

- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_other_region_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml
Depends on:
Aws targetted and full refresh specs for ebs storage manager
> Aws targetted and full refresh specs for ebs storage manager

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- spec/factories/cloud_volume.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
Recently Amazon introduced a capability to modify existing cloud volumes
on the fly. Depending on the volume type size, volume type and IOPS can
be modified without detaching the volume first.
This patch enhances the existing `update_volume` method that previously
allowed changing only the name of the volume by using the new method
`#modify_volume` from the aws-sdk gem. The patch also adds a set of
tests verifying different possible options passed to the
`update_volume`.
Depends on #176 (requires newer aws-sdk gem).
> Enable dynamic cloud volume modifications

- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
Counts specs mixin, extracting specs for count to a new mixin.
Instead of hardcoded numbers, that doesn't test much, we compare
our DB to the raw data we get from the API.
> Counts specs mixin

- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_object.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Current code always connects to S3's region that of cloud manager. This works fine when buckets that we're accessing are within that region, but results in error when accessing bucket from any other region.
With this commit we update provider_object for CloudObjectStoreContainer and CloudObjectStoreObject so that it now connects to appropriate region.
@miq-bot assign @bronaghs
> Connect to correct region with S3

- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
This PR was originally designed so that CloudObjectStoreContainer model stores `provider_region`. But a decision was made in https://github.com/ManageIQ/manageiq/pull/14242 to omit this field for now and instead query bucket region dynamically when user triggers operation. Hence this tiny adjustment.
> Adjust attribute set of newly created bucket

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
The support in the backend was already there but the missing `supports`
prevented UI from showing the corresponding menu item.
This screen shows the menu item for EBS volume
> Add support snapshot_create to EBS cloud volume

- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
Current implementation assumes that frontend composes all the options that backend then just sends to AWS. But there is an exception with :name option. While it is needed on frontend (to display flash), it is rejected by AWS.
Initial idea was to just remove the :name option here in backend, but turns out (see [this conversation](https://github.com/ManageIQ/manageiq-ui-classic/pull/651#discussion_r107285748)) that renaming it to :bucket works better. Hence this commit.
> Remap `:name` parameter into `:bucket` parameter when creating new bucket

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Depends on:
This adds tags for VM's and images.
The other half of this will happen in the core repo on the save_xxx side.
> Add tags for VMs and Images

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Return instead of next is causing unwanted break of Vm parsing
> Return instead of next is causing unwanted break of Vm parsing

- app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser.rb
Gracefully ignore and log errors when listing s3 objects and log them as a warning
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1439257
> Gracefully ignore and log errors when listing s3 objects

- app/models/manageiq/providers/amazon/cloud_manager.rb
- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
Depends on:
Ensure managers change zone and provider region with cloud manager
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1439268
> Ensure managers change zone and provider region with cloud manager

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/cloud_manager/virtual_template.rb
Removing Virtual Templates which are a part of arbitration which will soon be deleted from the main repo. (first PR for the removal process: https://github.com/ManageIQ/manageiq/pull/14776) 
@miq-bot add_label refactoring
> Remove Virtual Templates

- app/models/manageiq/providers/amazon/cloud_manager.rb
- config/settings.yml
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
- spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Add a configuration to the Settings.yml file that allows administrators to enable or disable Amazon S3 support.
The feature will be disabled by default.
Disabling S3 will disable the S3 manager, which will prevent the S3 refresh worker from starting.
> Make S3 a prototype feature

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Remove not needed :type from the parser, which is needed only
if we are storing sub STI classes under 1 InventoryCollection
definition. Otherwise the :type is taken from the
InventoryCollection of a Persister.
And test that we refresh the right STI classes.
> Remove not needed type from a parser

- app/models/authenticator/amazon.rb
- spec/models/authenticator/amazon_spec.rb
- spec/models/authenticator_spec.rb
This was the only code still using `aws-sdk` directly. Moving over here
https://github.com/ManageIQ/manageiq/pull/14492
cc @chessbyte
> move amazon authenticator from core to amazon repo

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Depends on:
Remove not needed type from an orch template parser
> Remove not needed type from an orch template parser

- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_object.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
On S3, folders are nothing but regular objects. However, deleting folder fails silently if there are any objects in it. To resolve this issue, we perform a batch delete of all objects within that folder.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1444079
@miq-bot assign @bronaghs 
> Support deletion of S3 folders

- app/models/manageiq/providers/amazon/manager_mixin.rb
Regions.names calls regions which calls
`Settings.ems.ems_amazon.try!(:additional_regions)).stringify_keys`
This Settings call was occurring at require time. We should not hit
Settings by just requiring files and that is what happens
previously.  This seems to cause a sporadic test failure [1]
perhaps because resetting the global constant Settings is very time
dependent and if we access it at the wrong time, it could be nil/not
initialized.
We can prevent this by delaying the Settings call until the validation
is called by wrapping the code in a lambda.
```
1) Metric as vmware with enabled and disabled targets executing perf_capture_timer should queue up enabled targets
Failure/Error: if (_klass = name.safe_constantize) # this triggers the load
NoMethodError:
undefined method `ems_amazon' …
```
> Wrap the validation Settings.ems call in a lambda

- app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_parser_spec.rb
Parse correct timestamp for AWS Alarm event
Test that we parse a timestamp for each event type, timestamp is needed for being able to display event in the timelines, also an event without timestamp can break timelines, if it's first or last event of the provider.
> Parse timestamp for aws alarm events

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
Amazon EBS API will throw an error in case `modify_volume` is called
with the options that do not differ from the current volume
configuration. This patch ensures that data is properly tested before
it's submitted to the API (if at all). Specs needed minor changes due to
this change; one more test was added to ensure that "no modifications
update" do not invoke the API.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449237
> Prevent volume update with no modifications

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/inventory/persister.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
Depends on:
Leverage builder params to provide ems_id and the defaults. That will simplify parsers logic and allow us to create placeholder objects using just ems_ref.
> Leverage builder params to provide ems id and defaults

- manageiq-providers-amazon.gemspec
This PR is a prerequisite for https://github.com/ManageIQ/manageiq-providers-amazon/pull/251
and https://github.com/ManageIQ/manageiq/pull/15107
Order of merge should be this one, then the core PR, then the next manageiq-providers-amazon PR listed above.
@bdunne @yrudman @bronaghs @roliveri @hsong-rh  Please review and merge asap.  Thanks.
> upgrade aws-sdk to 2.9.7

- app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
Depends on:
Simplify TargetCollection Persistor by using IC configurations
> Simplify TargetCollection Persistor by using IC configurations

- app/models/manageiq/providers/amazon/cloud_manager/vm.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
- manageiq-providers-amazon.gemspec
- spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
Add initial code to queue a scan request for instances and images by
via the amazon_ssa_support gem.   Update the
version of aws-sdk required for SSA requests.
This PR is dependent upon https://github.com/ManageIQ/amazon_ssa_support/pull/7 so that the requirement for an "extractor_id" when queuing a request will no longer be there.
It is also dependent upon https://github.com/ManageIQ/manageiq-providers-amazon/pull/252 which
upgrades the aws-sdk version to 2.9.7
It is also a dependent upon https://github.com/ManageIQ/manageiq/pull/15107.
because the Gemfile changes adding the amazon_ssa_support gem cannot be added in this Gem - they must be added in the core Gemfile.
@roliveri @hsong-rh @bronaghs please review.
Note this is WIP because I am still adding tests.
> Initial Changes to Amazon Provider for SSA Support

- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
Since they were not used in the UI, these two attributes were previously
not collected. Latest UI changes have introduced changes that show all
fields while editing existing cloud volumes, rendering them empty for
the users.
Depends on: https://github.com/ManageIQ/manageiq/pull/14704
@miq-bot add_label enhancement,pending core
> Collect IOPS and encryption status of cloud volume

- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_parser.rb
- spec/models/manageiq/providers/amazon/aws_stubs.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
UI has encrypted attribute included, but it is rendered empty for the user.
Depends on: https://github.com/ManageIQ/manageiq/pull/15352
> Collect encryption status of cloud volume snapshot

- Rakefile
- lib/manageiq/providers/amazon/engine.rb
Now, we don't require anything and I get to delete code.
~~Because we use isolate_namespace, we need to require action_controller/railtie. A blank rails engine generated by rails doesn't require anything...[1] Other engines do the sensible thing: require what they need [2] We shouldn't make assumptions about the rails features the application using the engine will want to use.~~
~~[1]
https://github.com/rails/rails/blob/0e453e9150f0ac9fa2bdff4511c3c806a3e45f49/railties/lib/rails/generators/rails/plugin/templates/lib/%25namespaced_name%25/engine.rb~~
~~[2] https://github.com/rails/coffee-rails/blob/db0659924c82f24e2665d799b1ab342078f2501d/lib/coffee/rails/engine.rb#L1~~
Note, I tested this by running the following:
```
05:50:14 ~/Code/manageiq-providers-amazon (dont_require_all_of_rails) …
```
> Require rails/engine and action_controller/railtie

- spec/requests/api/provision_requests_spec.rb
These were broken by the introduction of
https://github.com/ManageIQ/manageiq/pull/15430 and
https://github.com/ManageIQ/manageiq/pull/15186
@miq-bot add-label test, bug
@miq-bot assign @durandom
> Fix provision request specs

- app/models/manageiq/providers/amazon/cloud_manager/template.rb
Previously SSA was enabled for AWS Instances but not for Images.
This (extremely) simple change will turn on the support for Images as well.
@roliveri please review and approve.
@blomquisg @bronaghs please review and merge when appropriate.
> Enable SSA for AWS Images

- app/models/manageiq/providers/amazon/manager_mixin.rb
- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
The UI is moving towards validating credentials on the queue to allow for validating credentials in separate zones utilizing the `raw_connect` class method, rather than needing to create a temporary EMS for validation.
For many of the providers, `raw_connect` ensures the credentials are correct. This updates `raw_connect` to not only return a connection but also be able to validate (it will *not* validate by default).
Because credentials are going to be stored on the queue, it also needs to be able to decrypt them. This uses `MiqPassword.try_decrypt` so that it can accept both unencrypted and encrypted credentials.
PR with greater detail: https://github.com/ManageIQ/manageiq-ui-classic/pull/1580
> allow raw_connect to validate the connection and decrypt the password

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
It is possible for the name coming from a tag to be an empty string,
this was bypassing the ||= check but failing the validation on the
VmOrTemplate model causing the refresh to fail.
This same issue was fixed for instances by https://github.com/ManageIQ/manageiq-providers-amazon/pull/35
https://bugzilla.redhat.com/show_bug.cgi?id=1471297
> Handle empty string in image name tags

- spec/requests/api/provision_requests_spec.rb
The security_groups key now defaults to a data_type of `:array_integer`.  The resulting value is an Array of Integers as opposed to an array with the first value being an integer and the second being a human readable value.  
This fix modifies the resulting hash to expect an array of Integers.
Dependent on: https://github.com/ManageIQ/manageiq/pull/15572
> Adjust test result to match new data_type

- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
Previously the request to perform SSA on AWS by the Scanning Instance was implemented.
We are now implementing the code to process the response from the the SSA scan upon
completion.
Note that much of the code to do this, in perform_metadata_sync,
was taken from the ScanningMixin method scan_via_miq_vm.  The intent will be to
mitigate duplication when possible moving forward but for now we wanted to get
this running at the very least.
Also note that for now this code will be reading the first available response from
SQS.  If more than one SSA request is issued simultaneously there is a good chance
that the responses will be handled out of order.  We intend to implement a worker
to perform this task in the near future to handle this issue.
@roliveri and @hsong-rh please review for …
> Handle SSA Response from AWS Scanning Instance

- app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Enable to save key_pair information in authentication table. Smart state analysis will use it to transfer files to the agent.
> Enable to save key_pair in Authentication

- app/models/manageiq/providers/amazon/inventory/persister.rb
- app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_other_region_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
- spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Depends on:
Test all refresh strategies in aws using the options from Settings
> Test all refresh strategies in aws

- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Depends on:
Lower the batch sizes to also test multiple batches being processed
> Lower the batch sizes to also test multiple batches being processed

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/cloud_manager/refresh_worker.rb
this allows us to create an array of child managers for our queue.
> Overriding queue name to generate an array of queue names

- app/models/authenticator/amazon.rb
- spec/models/authenticator/amazon_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1489596
Fix authentication **mode:** _amazon_
This PR address a regression that was introduce by PR [15796](https://github.com/ManageIQ/manageiq/pull/15716) which
caused a regression in authentication preventing logins when the authentication
mode is configured for "Amazon"
1. Configure an appliance for authentication mode of "Amazon"
2. Configure an valid group on the appliance for a valid Amazon user.
2. Attempt to login with valid user credentials from the Amazon account.
> Do not downcase the amazon IAM username

- config/settings.yml
Turn on graph refresh with targeted refresh as default
Partially implements:
https://bugzilla.redhat.com/show_bug.cgi?id=1395356
----
related PRs for actually making targeted refresh work from automate event handlers
https://github.com/ManageIQ/manageiq-content/pull/178
https://github.com/ManageIQ/manageiq-content/pull/179
https://github.com/ManageIQ/manageiq-automation_engine/pull/67
> Turn on graph refresh with targeted refresh as default

- app/models/manageiq/providers/amazon/instance_types.rb
- config/settings.yml
- lib/tasks_private/instance_types.rake
- spec/models/manageiq/providers/amazon/instance_types_spec.rb
Allow user to add instance_types that MIQ doesn't include. These are types that added by AWS after MIQ's code freeze for release.
> Support custom instance_types

- app/models/manageiq/providers/amazon/cloud_manager/orchestration_template.rb
- spec/factories/orchestration_template.rb
- spec/fixtures/orchestration_templates/cfn_parameters.json
- spec/fixtures/orchestration_templates/cfn_parameters.yaml
- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
The primary purpose of this work is to accept YAML format content as an OrchestrationTemplate. It also refactors the spec tests to move sample templates from manageiq repo to amazon repo.
https://bugzilla.redhat.com/show_bug.cgi?id=1417021
> Add YAML support for Amazon OrchestrationTemplate

- app/models/manageiq/providers/amazon/cloud_manager/orchestration_template.rb
- spec/models/dialog/orchestration_template_amazon_service_dialog_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
After https://github.com/ManageIQ/manageiq/pull/16047 the use of TextArea requires the constraint `OrchestrationParameterMultiline`. This work fix the stack options for AWS Cloudformation deployment that require a text area.
> Add OrchestrationParameterMultiline constraints to options that require a text area

- app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
Compact targeted refresh references, AWS API will throw en rror
if there is nil among them.
> Compact targeted refresh references

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot_spec.rb
Add raw_delete_snapshot function. This function is now called from snapshot_delete, which was moved to core model together with snapshot_delete_queue.
This PR is replacement for: https://github.com/ManageIQ/manageiq-providers-amazon/pull/260
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1449243
Depends on: https://github.com/ManageIQ/manageiq/pull/15624
> Add raw_delete_snapshot to CloudVolumeSnapshot model

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
Overview/plan issue: ManageIQ/manageiq-providers-kubernetes#126
To be merged **simultaneously** with ManageIQ/manageiq#16098 and ManageIQ/manageiq-providers-kubernetes#130.  Can't pass Travis until the core PR lands.
Expose mapper to save_inventory_container which will use it to find/create all referenced tags.
@djberg96 please review.
> Use new ContainerLabelTagMapping::Mapper interface

- app/models/manageiq/providers/amazon/agent_coordinator_worker/runner.rb
- app/models/manageiq/providers/amazon/agent_coordinator_worker/runner/response_thread.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
- config/settings.yml
Add the Amazon SSA response thread which will be integrated with the
AgentCoordinatorWorker.  This thread checks the SQS queues set up
by the Amazon SSA Agents to see if any SSA responses have been added.
If so the responses are pulled out of the appropriate S3 buckets and
processed.  The appropriate Job is then updated with the status.
This PR is dependent upon https://github.com/ManageIQ/manageiq-providers-amazon/pull/318
and should neither be merged nor have any tests run on it until such time as the dependent PR is merged.
@Fryguy @hsong-rh @roliveri @bronaghs please review now so we are ready to merge in a timely manner.  Thank you.
> Amazon SSA Response Handling Thread

- app/models/manageiq/providers/amazon/agent_coordinator_worker/runner.rb
The ResponseThread "include" statement was inadvertantly left out of the Runner
for the AgentCoordinatorWorker when it was ported out of the ManageIQ repo
into the manageiq-provider-amazon repo in https://github.com/ManageIQ/manageiq-providers-amazon/pull/319.  This PR adds it back in.
@Fryguy you found this issue - this fixes it.  Please review and merge.
@roliveri @hsong-rh @bronaghs fyi - one line fix for an omitted line of code.
> Include ResponseThread in Runner

- app/models/manageiq/providers/amazon/cloud_manager.rb
Add the additional smartstate_docker authentication type
to be used for Docker Registry login on the remote AWS instance running smart state.
This change goes hand-in-hand with the [UI PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/2525) under separate cover which relies on this to succeed.
@roliveri @hsong-rh @Fryguy @bronaghs please review and merge when ready.
> Add smartstate_docker authtype

- app/models/manageiq/providers/amazon/agent_coordinator.rb
- app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
- app/models/manageiq/providers/amazon/agent_coordinator_worker/runner.rb
- config/settings.yml
This PR contains the following changes:
1. Start AgentCoordinatorWorker only when role of 'smartproxy' is enabled and Amazon provider exists;
2. Add register flag for both docker register and Redhat downstream register;
3. Change KeyPair name into uniq, so different users from the same AWS account use their own key pair.
4. Other changes based on reviewers' comments.
> Various changes for SSA support

- app/models/manageiq/providers/amazon/agent_coordinator.rb
Add wait_until to make sure instance_profile is created and ready to be used.
> Add wait_until_exists on instance_profile creation

- app/models/manageiq/providers/amazon/manager_mixin.rb
the verify_credentials method was failing for smartstate_docker credentials
which resulted in the provider being added with valid unchecked credentials
but the first time the scheduled credentials verification ran the provider
became invalid.  Changed to always return true for these credentials
which allows the provider to be valid.
This is related to but not exactly the same as issue https://github.com/ManageIQ/manageiq-providers-amazon/issues/335.
@roliveri @hsong-rh @fryguy please review and merge for today's build.  Thanks.
> Verify Smartstate Credentials Should ALways Return True

- app/models/manageiq/providers/amazon/agent_coordinator_worker/runner.rb
- app/models/manageiq/providers/amazon/agent_coordinator_worker/runner/response_thread.rb
Change the includes/requires for the AgentCoordinatorWorker::Runner::ResponseThread to use include_concern.
This issue was called out by @Fryguy on the initial PR for the ResponseThread for Amazon Smartstate - https://github.com/ManageIQ/manageiq-providers-amazon/pull/319.  Fixing this for the build today.
@Fryguy @roliveri @hsong-rh please review.  Merge when appropriate.
> Use Concern for ResponseThread include

- app/models/manageiq/providers/amazon/cloud_manager.rb
Addresses an issue where the EMS association between the cloud manager and storage manager were not established when upgrading from 5.7 to 5.8, resulting in no storage information displayed in the UI.
https://bugzilla.redhat.com/show_bug.cgi?id=1480629
The DB migration was already taken care of by @Fryguy in https://github.com/ManageIQ/manageiq-schema/pull/117
> [FINE] Add seed method for Amazon cloud manager

- app/models/manageiq/providers/amazon/cloud_manager/orchestration_stack.rb
- app/models/manageiq/providers/amazon/cloud_manager/orchestration_template.rb
- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1503781
According to AWS SDK document `on_failure` and `timeout_in_minutes` are not in the list of arguments the `stack#update` method would expect.
Also modify the deployment options in the service dialog so that `stack_onfailure` and `stack_timeout` are disabled when a user reconfigures a stack.
> exclude on_failure and timeout_in_minutes when update a stack

- app/models/manageiq/providers/amazon/cloud_manager/refresh_worker.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresh_worker_spec.rb
Queue name order is important to allow arrays of queue_names to work
like a single string queue_name.
This PR is related to https://github.com/ManageIQ/manageiq/commit/db6a096ebd97d09ab0a58d41c5518e3f69a46d58
Fixes BZ # https://bugzilla.redhat.com/show_bug.cgi?id=1500429
cc @juliancheal
> Always sort ems queue names before hitting miq_queue

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Deals with the possibility of an empty string for a `Name` tag, which is defeating our `||=` logic.
I borrowed Adam's solution from https://github.com/ManageIQ/manageiq-providers-amazon/pull/273, just for the inventory side.
https://bugzilla.redhat.com/show_bug.cgi?id=1471297
> Handle possibility of empty string for Name tag

- app/models/manageiq/providers/amazon/agent_coordinator.rb
Amazon smartstate agent needs to have public DNS when it is deployed. This requires its VPC host must have DNS support enabled. 
This PR adds the logic to check existing VPCs, choose the one with DNS support enabled, then deploy an agent on it. 
https://github.com/ManageIQ/manageiq-providers-amazon/issues/355
> Choose VPC with enabled DNS support to deploy SSA Agent

- app/models/manageiq/providers/amazon/agent_coordinator.rb
The fix in https://github.com/ManageIQ/manageiq-providers-amazon/issues/365 adds a new check.  When generating Amazon key pair, the hash parameter create_options has to have :name set, rather than key_name before.  This causes Amazon SSA support failed to create key pair.
https://bugzilla.redhat.com/show_bug.cgi?id=1514192
> Use name to create key pair

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/persister.rb
- app/models/manageiq/providers/amazon/inventory/persister/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
- app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
Subsumes #384, done with lots of help from Ladislav & Julian :earth_africa: 
https://bugzilla.redhat.com/show_bug.cgi?id=1506404
cc @bronaghs @djberg96 @Ladas @agrare (in case anybody still here, and happy holidays)
> Implement tag mapping in graph refresh

- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
Test that targeted refresh stays in its scope and it doesn't
delete anything out of its scope. And test correct counts of taggings.
Add specs for https://bugzilla.redhat.com/show_bug.cgi?id=1506404
> Test that targeted refresh stays in its scope

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/cloud_manager/orchestration_stack.rb
- app/models/manageiq/providers/amazon/cloud_manager/orchestration_template.rb
- app/models/manageiq/providers/amazon/cloud_manager/template.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm.rb
- app/models/manageiq/providers/amazon/network_manager.rb
- app/models/manageiq/providers/amazon/network_manager/cloud_network.rb
- app/models/manageiq/providers/amazon/network_manager/cloud_subnet.rb
- app/models/manageiq/providers/amazon/network_manager/floating_ip.rb
- app/models/manageiq/providers/amazon/network_manager/load_balancer.rb
- app/models/manageiq/providers/amazon/network_manager/network_port.rb
- app/models/manageiq/providers/amazon/network_manager/security_group.rb
This is a continuation of the work started in https://github.com/ManageIQ/manageiq/pull/16596 where we want to migrate display model names from locale/en.yml into particular models, where we'll use standard gettext. Main goal here is to make this one aspect of our application pluggable.
Core PR: https://github.com/ManageIQ/manageiq/pull/16836
> Migrate model display names from locale/en.yml to plugin

- app/models/manageiq/providers/amazon/regions.rb
- spec/vcr_cassettes/manageiq/providers/amazon/regions.yml
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1531910
> Added Paris (EU) region

- app/models/manageiq/providers/amazon/cloud_manager.rb
Destroying child_managers is orchestrated by the parent and destroying
them prematurely leads to issues when the endpoints are shared between
the two managers.
Example failure: https://travis-ci.org/ManageIQ/manageiq-providers-openstack/jobs/332446792#L2079-L2091
Depends: https://github.com/ManageIQ/manageiq/pull/16871
> Don't dependent => destroy child_managers

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/inventory/persister/storage_manager/ebs.rb
Depends on:
Use proper nested references in parser. Adding nested
lazy_finds to correctly model a complex link.
> Use proper nested references in parser

- app/models/manageiq/providers/amazon/network_manager/network_router.rb
This PR is to bring the changes from https://github.com/ManageIQ/manageiq/pull/16912 into the provider plugin (for consistency).
> Add display_name() for Network Router model

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- spec/models/manageiq/providers/amazon/cloud_manager/specific_stubbed_refresher_spec.rb
Fix refresh for stack without parameters and add specs for
more combinations of missing stack relations.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544863
> Fix refresh for stack without parameters

- app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb
Return created topic instead of log.info, which always returns true.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1545147
> Return created topic

- app/models/manageiq/providers/amazon/agent_coordinator.rb
In the case that the AMI in AWS that is to be used for Smartstate is not visible
to the user, raise a meaningful error which will be visible in the log.
Previously this resulted in a nil object and a stack trace which was confusing in the least.
In a separate PR we will look at marking any jobs waiting for the agent to be deployed
as failed when this happens but this current PR should be merged first.
@roliveri @hsong-rh please review.  Thanks.
> Raise Exception if AMI not visible

- app/models/manageiq/providers/amazon/agent_coordinator.rb
When the AMI specified for the AWS Smartstate Scanning Agent Instance is not available,
the Smartstate job cannot run.  Instead of having any Smartstate requests
sit on the job queue until they time out, mark them as aborted due to the missing AMI failure.
@roliveri @hsong-rh please review and merge when appropriate.
> Cleanup Smartstate Requests When AMI Unavailable for Agent

- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_stack_spec.rb
ManageIQ has its own `have_attributes` which has diverged from upstream rspec's. It'll go away at some point, for now shows warning (see https://github.com/ManageIQ/manageiq/pull/16188):
```
Randomized with seed 13795
............................................................................
WARNING: Use of `have_attributes` with array access (:[]) is deprecated and will be removed shortly.
If you're matching attributes in hashes, use appropriate hash matchers instead (`include`, `eq`).
Called from /home/bpaskinc/miq/quota-scopes/plugins/manageiq-providers-amazon/spec/models/manageiq/providers/amazon/cloud_manager/orchestration_stack_spec.rb:119:in `block (5 levels) in <top (required)>'
```
Using `include` will work when we drop the custom matcher.
> Fix deprecated use of `have_attributes`

- spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb
Amazon's allowed_cloud_networks needs test for RBAC filtering from PR [here](https://github.com/ManageIQ/manageiq/pull/16824/files)
> Tests cloud_networks with RBAC filtering from super

- app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
- app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/cloud_manager/refresh_parser_spec.rb
Fix passing of the default filter for the `get_public_images` and `public_images` methods.
The validation in `aws-sdk` prevents passing object of `Config::Options` type and requires `Hash` instead, e.g.:
```ruby
:filters => [{:name=>"image-type", :values=>["machine"]}]
:filters => [#<Config::Options name="image-type", values=["machine"]>]
```
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1554914
Also additional test coverage for the public image filter should follow.
@miq-bot add_label bug, gaprindashvili/yes, inventory
> Fix default filter for public images

- app/models/authenticator/amazon.rb
- app/models/manageiq/providers/amazon/manager_mixin.rb
- lib/patches/aws-sdk-core/seahorse_client_net_http_pool_patch.rb
There is a bug with the aws-sdk that prevents the API from working properly when using a proxy, and the auth for the proxy includes a special character (like a question mark: `?`).  This is described here:
https://github.com/aws/aws-sdk-ruby/pull/1760
Since the release of the fix in `aws-sdk` is unknown, this currently monkey patches the fix to MIQ to allow it to work without it.
TODO
----
Links
-----
* Pull-request for the patch in lib:  https://github.com/aws/aws-sdk-ruby/pull/1760
* Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567418
QA Steps
--------
* Add a proxy for `:ec2` in the advanced config.  Make sure either the `:user:` and/or `:password:` has a special character in it (`?` works for example):
```
:http_proxy:
:ec2:
:host: <<PROXY_HOST>>
:port: <<PROXY_PORT>>
:user: …
```
> Add patch to aws-sdk-core to fix auth bug

- app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
- app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/network_manager/refresh_parser_spec.rb
Update firewall rules parsing with:
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1540283
AWS Documentation: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html
Related: https://github.com/ManageIQ/manageiq-ui-classic/pull/3710
@miq-bot add_label bug, inventory
> Fix firewall rules parse

- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
**The PR should be merged together with the PR to the core repo: https://github.com/ManageIQ/manageiq/pull/17143**
---
Related to the changes in:
https://github.com/ManageIQ/manageiq/pull/17143
https://github.com/ManageIQ/manageiq-ui-classic/pull/3607
cc @miha-plesko
> Renamed method for consistency reasons

- app/models/manageiq/providers/amazon/network_manager.rb
- spec/models/manageiq/providers/amazon/network_manager_spec.rb
Currently the Amazon provider does not explicitly disable EMS network creation and editing. Based on the current UI code, as well the Nuage provider code, support for `:ems_network_new` should be disabled.
Note that this will also require at least one code change on the classic UI side. Please see https://github.com/ManageIQ/manageiq-ui-classic/pull/3976, which properly uses the `SupportsFeatureMixin` hook.
While I was here I also added the beginnings of a test suite for the Amazon NetworkManager.
Partial fix for https://bugzilla.redhat.com/show_bug.cgi?id=1577888
> Explicitly disable ems_network_new creation

- app/models/manageiq/providers/amazon/manager_mixin.rb
- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
This adds a uri endpoint argument to the `raw_connect` method. It is nil by default, but if present it will be passed to the AWS connection code.
Note that this PR depends on a change on the classic UI side. The UI change will add an endpoint text field, which is handled as a URI object, and its parts saved to the `endpoints` table.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1339398
See also: https://github.com/ManageIQ/manageiq-ui-classic/issues/3907
> Add endpoint support to raw_connect

- spec/models/authenticator/amazon_spec.rb
The new audit_failure method in authenticator/base raises an evm event
on auth failure which targets the MiqServer.my_server.  In the amazon
authenticator spec this was nil which was causing the audit_failure
method to throw an exception trying to get class and id from the target.
https://bugzilla.redhat.com/show_bug.cgi?id=1318353
> Fix missing MiqServer in Authenticator spec

- app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb
- app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb
- app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/config/EBS_Snapshot_Notification.json
- spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1561937
Related: https://github.com/ManageIQ/manageiq-content/pull/285
Note:
AWS CloudWatch should send specific events. 
To setup, one should create CloudWatch rule and target it to the `AWSConfig_topic` SNS topic.
This rule's event pattern should be:
```json
{
"source": [
"aws.ec2"
],
"detail-type": [
"EBS Snapshot Notification"
]
}
```
More info: https://aws.amazon.com/ru/blogs/aws/new-cloudwatch-events-for-ebs-snapshots
> handle volume snapshot status changes

- app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1418481
When a local user auth key is created that can be deleted, but not
ones imported from the provider.
> Added allow_delete method on AuthKeyPairs

- db/fixtures/aws_instance_types.yml
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1590288#c6
There was a bare metal instance in the virtual instance types list. Now it removed.
> remove bare metal instance

- spec/models/authenticator/amazon_spec.rb
Recieved from this PR https://github.com/ManageIQ/manageiq/pull/17852
> Add in missing user creation audit event.

- app/models/manageiq/providers/amazon/cloud_manager/refresher.rb
- app/models/manageiq/providers/amazon/inventory.rb
- app/models/manageiq/providers/amazon/inventory/collector.rb
- app/models/manageiq/providers/amazon/inventory/parser.rb
- app/models/manageiq/providers/amazon/inventory/persister.rb
Move away from the compatibility ManagerRefresh::Inventory class to ManageIQ::Providers::Inventory
> Move Inventory from ManagerRefresh to ManageIQ::Providers

- db/fixtures/aws_instance_types.yml
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
announces:
- https://aws.amazon.com/about-aws/whats-new/2018/08/introducing-amazon-ec2-t3-instances
- https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-ec2-f1-instances-now-available-in-an-additional-size
8 new types in total
> new AWS EC2 instance types

- config/settings.yml
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
@Fryguy @Ladas somehow we missed one provider.
Symbols in configuration values are problematic because Symbols do not
roundtrip through JSON.  Since the API now exposes Settings, it's not
possible to set Symbols as values.  The saver_strategy was fixed in
ManageIQ/manageiq#17168 to support String
values, and the next step is to remove all Symbols from the Settings.
ManageIQ/manageiq#17201
https://bugzilla.redhat.com/show_bug.cgi?id=1558031
@miq-bot add-labels bug, gaprindashvili/yes, hammer/yes
> Change saver_strategy value to String

- spec/models/dialog/orchestration_template_amazon_service_dialog_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1642594
Fixes CI build failure caused by https://github.com/ManageIQ/manageiq/pull/18202
> Service dialog for orchestration template no longer contains tenant selection

- app/models/manageiq/providers/amazon/cloud_manager/vm.rb
Memory chart is not showing for Amazon Instances in UI.
` ManageIQ::Providers::Amazon::CloudManager::Vm` is returning false for `memory_mb_available?` and that is the reason why the memory chart is not showing im UI.
This behavior is inherited from `VmOrTemplate` `non_generic_charts_available?` method.
https://bugzilla.redhat.com/show_bug.cgi?id=1676761
@Ladas I am not sure if this is the correct fix, so please feel free to correct me ;)
> Return true for memory_mb_available?

- config/settings.yml
@agrare @djberg96 this is a very simple change, just hide a new us-gov region by default, as we do that with other special regions.
> disable new us-gov region by default

- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
- spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
- spec/tools/refresh_performance/aws_refresh_performance_cloud_manager.rb
- spec/tools/refresh_performance/aws_refresh_performance_network_manager.rb
Now that ManageIQ/manageiq#18633 is merged we can update this to only look for CloudManager::AuthKeyPairs
> Update specs to look for CloudManager::AuthKeyPair

- app/models/manageiq/providers/amazon/cloud_manager/orchestration_service_option_converter.rb
- spec/models/manageiq/providers/amazon/cloud_manager/orchestration_service_option_converter_spec.rb
To pass the validation on timeoutInMinutes that the value must be greater than or equal to 1.
https://bugzilla.redhat.com/show_bug.cgi?id=1698439
cc @gmcculloug
> Return not set timeout in dialog as nil instead of 0.

- spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
On Rails 5.1, this raises an ArgumentError.
```
1) ManageIQ::Providers::Amazon::StorageManager::Ebs::CloudVolume cloud volume operations .raw_create_volume creates a volume
Failure/Error: ext_management_system = ExtManagementSystem.find(ems_id)
ArgumentError:
You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`.
```
> Pass id to AR::Base find, not AR::Base objs

- .codeclimate.yml
See ManageIQ/manageiq#18840 for more information
Unfortunately there's no way to use a centralized .codeclimate, so we have to configure the configuration files individually.
> Add rubocop channel to codeclimate config

- app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
This PR is reverting https://github.com/ManageIQ/manageiq-providers-amazon/pull/457 as that is causing an issue in deleting auth keys created, without a public key.
Also https://github.com/ManageIQ/manageiq-providers-amazon/pull/457 doesn't even seem to solve the issue of the bug it was suposed to be fixing.
This PR fixes BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1718833
/cc @AlexanderZagaynov @agrare
> Remove allow_delete logic

- app/models/manageiq/providers/amazon/cloud_manager.rb
This is a follow-up for https://github.com/ManageIQ/manageiq-providers-amazon/pull/538 as demanded by UI team (https://github.com/ManageIQ/manageiq-ui-classic/pull/5621).
> use 'supports?' feature for assume role field

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/manager_mixin.rb
Add a set of parameters required by the UI to drive their data-driven-forms and implement the common validate_credentials API instead of raw_connect.
> Add JSON-Schema create-params and a common Validate Credentials API

- app/models/manageiq/providers/amazon/cloud_manager/provision/state_machine.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm/operations.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm/operations/guest.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm/operations/power.rb
update_attributes and update_attributes! are deprecated starting in Rails 6
See https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/ for details and Rails PR links.
> Update attrs deprecation

- app/models/manageiq/providers/amazon/manager_mixin.rb
Update the name of the method to be inline with the core
verify_credentials method, ensure that the method only returns a
boolean not the raw connection, and decrypt the password field if it is
encrypted.
https://github.com/ManageIQ/manageiq/issues/18818
> Rename validate_credentials to verify_credentials

- spec/models/authenticator/amazon_spec.rb
The find_by_* methods defined in manageiq repo has conflicts with
rails dynamic finding and now they have been changed to lookup_by_*
Switching the callers in this repo to the lookup_by_ methods.
Depend on ManageIQ/manageiq#19313
> Switch find_by_* to lookup_by_

- spec/models/authenticator/amazon_spec.rb
Rspec is not allowing expect to take a lambda as an argument anymore
> Fix rspec expect taking a lambda as an argument

- app/models/manageiq/providers/amazon/cloud_manager.rb
Prevent people from using the constant directly by defining
`@params_for_create ||= {}.freeze`
> Replace PARAMS_FOR_CREATE constant with @ ||=

- bin/setup
If a MANAGEIQ_REPO env var is passed to bin/setup then symlink that repo
to spec/manageiq instead of cloning a new copy.  This makes it possible
to test cross-repo changes with a plugin.
> Optionally symlink a core repo in bin/setup

- app/models/manageiq/providers/amazon/cloud_manager.rb
All of these operations are overridden by the Vm subclass so there is no need to have the "parent" operations defined since run_command_via_parent isn't actually called.
https://github.com/ManageIQ/manageiq/pull/19452
> Move raw_ vm operations to providers

- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
The ems_ref_obj attribute is going to be removed in the near future,
also it isn't necessary to check that it is nil
> Remove checking for ems_ref_obj => nil

- app/models/manageiq/providers/amazon/network_manager/refresh_worker.rb
- app/models/manageiq/providers/amazon/network_manager/refresh_worker/runner.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_worker.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_worker/runner.rb
Refresh of network and storage managers except for S3is handled
by the cloud manager refresh worker
cc @agrare 
see also: https://github.com/ManageIQ/manageiq/pull/19524
> Remove unused sub-manager refresh workers

- app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
This is needed in order to seed the MiqWorkerType model
> Add worker kill priority to the AgentCoordinatorWorker

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/cloud_manager/scanning.rb
- app/models/manageiq/providers/amazon/cloud_manager/scanning/job.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
State Machine diagram for this subclass of VmScan.
> Subclass VmScan job as ManageIQ::Providers::Amazon::CloudManager::Scanning::Job

- app/models/manageiq/providers/amazon/cloud_manager/metrics_capture.rb
- spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb
amazon is a cloud metrics capture class. subclassing the proper parent
part of https://github.com/ManageIQ/manageiq/pull/19684
> Subclass CloudManager metrics capture

- app/models/manageiq/providers/amazon/cloud_manager.rb
This is a followup based on discussions with @hyperkid123 and earlier in Mahwah with @Fryguy and @agrare. I removed the `name` and `zone` fields as they will be provided by the add provider form in order to decrease redundancy among forms. We can still reverse out from this solution, but in any case, the ordering of fields should and will be a little different. Common stuff has to go first, we can't implement jumping inconsistencies in DDF nicely.
I also added i18n calls on the strings, so @mzazrivec can consume them.
**Old form:**
**New form:**
Note that the bottom screenshot doesn't show the `name`, `type` and `zone` fields in the correct order, because I'm using the schema from https://github.com/ManageIQ/manageiq-ui-classic/pull/6402.
There are still stuff missing:
Parent issue: …
> Make the DDF fields more similar to the current form's layout + i18n

- app/models/manageiq/providers/amazon/cloud_manager.rb
I missed this from https://github.com/ManageIQ/manageiq-providers-amazon/pull/586 sorry :sweat_smile: 
> Rename aws-endpoint-valid to endpoints.default.valid in DDF schema

- app/models/manageiq/providers/amazon/manager_mixin.rb
The verify_credentials method wasn't checking that the AWS connection
was able to execute any commands.
Fixes https://github.com/ManageIQ/manageiq-providers-amazon/issues/587
> Fix verify_credentials always returning true

- spec/models/manageiq/providers/amazon/aws_helper.rb
We are going through Aws.config to look for services without requiring anything to pull in Aws (which is defined in aws-sdk-core).
> Require aws-sdk-core in aws spec helper

- app/models/manageiq/providers/amazon/cloud_manager.rb
With the current codebase, the `authtype` for the credentials is set to `nil`, while it should be default. When creating the provider through the old forms, it is being set to `default`.
> Include authtype when creating provider through DDF/API

- app/models/manageiq/providers/amazon/agent_coordinator.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
We don't need ssa support when we load the provider.  We can load this when we
need it.  Just loading the Amazon provider was costing 1-2 seconds, 20-40 MB depending on
what files were already loaded, and loaded an additional 512 files.
Before:
```
irb(main):001:0> ManageIQ::Providers::Amazon::AgentCoordinator
=> ManageIQ::Providers::Amazon::AgentCoordinator
irb(main):002:0> $LOADED_FEATURES.length
=> 3539
209.5 MB rails console.
```
After:
```
irb(main):001:0> ManageIQ::Providers::Amazon::AgentCoordinator
=> ManageIQ::Providers::Amazon::AgentCoordinator
irb(main):002:0> $LOADED_FEATURES.length
=> 3027
162.2 MB rails console.
```
Note, I needed this hack to load rails console from this repo's directory:
```diff
diff --git a/bin/rails b/bin/rails
index 183a93e..e0ba6af 100755
--- …
```
> Delay load ssa support

- app/models/manageiq/providers/amazon/cloud_manager.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream_spec.rb
When using create_from_params make sure to create endpoints as well as
authentications.
https://github.com/ManageIQ/manageiq-providers-amazon/issues/594
> Create ems.endpoints when using create_from_params

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/manager_mixin.rb
Providers have two extra underlying models (endpoints and authentications) storing data that we are displaying in the provider forms. In order to be able to pull in the data from the API to the edit provider forms more effectively, the DDF schema fields have to be named properly. 
There's an [API PR](https://github.com/ManageIQ/manageiq-api/pull/741) that allows to load these underlying models for a given provider and there's a [UI PR](https://github.com/ManageIQ/manageiq-ui-classic/pull/6698) that works with these data and prefills them into the form that is described in this PR. 
Of course these changes in the schema required some modifications in the validation and creation methods to have them still working.
https://github.com/ManageIQ/manageiq-ui-classic/pull/6698 …
> Adjust the DDF schema to be more similar to the DB schema

- app/models/manageiq/providers/amazon/cloud_manager.rb
This component has been [renamed](https://github.com/ManageIQ/manageiq-ui-classic/pull/6704) just to make provider forms and provider developers' life easier. It supports editing and it never contains the actual password.
Hopefully there will be no more schema changes, just the edit method :pray: 
> Change provider form password field to a password-field component

- app/models/manageiq/providers/amazon/manager_mixin.rb
When validating an existing provider, we don't want to send down the password to the browser. MartinM already created a component that sorts out this problem, basically the password field is a dummy and if it's untouched, it never gets submitted with the rest of the form. However, this causes issues with the validation.
My solution is to [pass the `id`](https://github.com/ManageIQ/manageiq-api/pull/751) of the provider to the validation task if available and retrieve the password using this ID if there is no submitted password.
@agrare @Fryguy we talked about this in Mahwah, what do you think? It's a little problemmatic that the retrieval is implemented in the provider, but the endpoints are different and some providers even have more than one, so there's no simple way to do this.
Parent …
> Retrieve the password from the DB when validating an existing EMS

- app/models/manageiq/providers/amazon/cloud_manager.rb
Newly DDF doesn't want to send me the empty object for the endpoints, so I created a fallback to make sure that the default one is always created.
> Fall back with default endpoint in DDF if nothing comes from the API

- spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb
The AWS Metrics Capture is using end_time - 4.hours which is different from the core 4.hours.ago.utc.beginning_of_day default that core is now using.
> Fix metrics_capture_spec vcr cassettes

- spec/models/manageiq/providers/amazon/aws_stubs.rb
This removes a couple invalid partials that causes errors if strict partial validation is enabled. In this case, objects are stubbing methods that they don't actually implement. With these removed, the specs still pass.
> Remove invalid partials in Amazon specs

- app/models/manageiq/providers/amazon/cloud_manager/provision/cloning.rb
During AWS provisioning, I have been experiencing  intermittent errors indicating invalid instance IDs ( longer trace attached ):
`MIQ(ManageIQ::Providers::Amazon::CloudManager::Provision#provision_error) [[Aws::EC2::Errors::InvalidInstanceIDNotFound]: The instance ID 'i-xxxxxxxxxxxx' does not exist] encountered during phase [poll_clone_complete]`
These requests did not include additional network interfaces. The solution posted to a similar issue - https://access.redhat.com/solutions/3638601 - did not help in my case.
This appears to be because the clone_task_check did not check if the instance existed before getting instance status. Since implementing this PR in my environment, I have not encountered errors during AWS provisioning. …
> Check instance exists before getting status during provisioning

- app/models/manageiq/providers/amazon/inventory/persister.rb
- app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
There was a pointless overridden Persister#initialize method and manager_uuids for key_pairs that are already added by the builder
> Remove the overridden persister initialize

- app/models/manageiq/providers/amazon/agent_coordinator.rb
- app/models/manageiq/providers/amazon/cloud_manager/metrics_capture.rb
- app/models/manageiq/providers/amazon/inventory/collector.rb
- app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/collector/network_manager.rb
- app/models/manageiq/providers/amazon/inventory/collector/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb
- app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
The aws-sdk v3 list calls cap out at 100 records per call. You either have to manually iterate using a next token, or explicitly force pagination via an iterator. Since we're dealing with hash results, that means calling `flat_map`.
```
Example using our current test environment:
aws = Aws::EC2::Client.new(region: 'us-east-1')
results1 = aws.describe_instance_types.instance_types
results2 = aws.describe_instance_types.flat_map(&:instance_types)
p results1.size # 100
p results2.size # 258
```
So, this PR goes through and updates the `describe_` and `list_` calls to explicitly use `flat_map`.
> Force pagination of results for V3 library

- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Should be `CloudManager` instead of `NetworkManager` in spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb.
> Fix cloud manager refresher spec described class name

- app/models/manageiq/providers/amazon/cloud_manager.rb
We can directly send the `zone_id` instead of sending the `zone_name` and looking it up explicitly when handling the API payload. 
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
> Use `zone_id` instead of `zone_name` in the DDF form

- spec/factories/ext_management_system.rb
It seems we must use a symbol now to access `Rails.application.secrets` provider info.
I'm not sure when it changed, but futzing on the rails console confirms that this works:
`Rails.application.secrets.amazon.try(:[], 'client_id') # nil`
vs
`Rails.application.secrets.amazon.try(:[], :client_id) # stuff`
> Use symbols instead of strings for accessing secrets

- app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb
- app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
- spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested_with_vm.yml
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_floating_ip_and_lbs_full_refresh.yml
- spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_public_ip_and_template.yml
Currently classic EIP's in AWS are not getting picked up by targeted refresh. This is because not all AWS floating IP resources have an `allocationId`. Specifically, a "classic" elastic IP will not have an `allocationId`. But, they do have an IP address.
Consequently, I've updated the targeted refresh collection and event parser to look at both `publicIp` and `allocationId` fields. I felt it was best to look for both, since in some cases the `ems_ref` could be either one since the parser looks for both.
~~The only downside to this is that I could no longer use filters, since the AWS SDK treats multiple filters as an AND rather than an OR, and I could see no way to do that within the SDK API. As a result, I'm filtering with pure Ruby after the fact.~~
Edit: Switched to multiple calls with …
> Update Floating IP target and event collection

- app/models/manageiq/providers/amazon/cloud_manager.rb
The `create_from_params` and `edit_with_params` are no longer necessary since https://github.com/ManageIQ/manageiq/pull/20157
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
> Adjusted DDF schema and removed create/edit methods

- app/models/manageiq/providers/amazon/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/storage_manager/s3.rb
Allow all associations required to edit a cloud_volume to be callable from the storage_manager without having to go to the parent_manager.
This allows for cloud_volumes that don't belong to a storage manager to be handled the same was as amazon cloud_volumes which do.
The current query is:
```
return API.get('/api/providers/' + id + '?attributes=type,supports_cinder_volume_types,supports_volume_resizing,supports_volume_availability_zones,parent_manager.volume_availability_zones,parent_manager.cloud_tenants,parent_manager.cloud_volume_snapshots,parent_manager.cloud_volume_types')
```
So the collections being requested from the parent_manager are:
* volume_availability_zones
* cloud_tenants
* cloud_volume_snapshots
* cloud_volume_types
The last two are actually delegated back to the storage …
> Delegate storage_manager.cloud_tenants to the cloud_manager

- app/models/manageiq/providers/amazon/cloud_manager/event_catcher/runner.rb
The do_before_work_loop [starts the event monitor](https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/base_manager/event_catcher/runner.rb#L59).
This [spins up the thread](https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/base_manager/event_catcher/runner.rb#L155-L169) and [waits for it to be started](https://github.com/ManageIQ/manageiq/blob/master/app/models/manageiq/providers/base_manager/event_catcher/runner.rb#L171).  The amazon event catcher only sets the started event to true [once an event is raised](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/app/models/manageiq/providers/amazon/cloud_manager/event_catcher/runner.rb#L11).
This means if you try to stop the event catcher before an event occurs you have …
> Set the monitor_running event to unblock the main thread

- app/models/manageiq/providers/amazon/inventory/parser.rb
- app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Currently the `name` field for network interfaces is defaulting to the ems_ref. This is unlike most other resources that use a `name` tag if found. Similarly, security groups are not currently using a `name` tag, so I updated that as well.
Oddly, network_interfaces use a `tag_set` field instead of a `tags` field like most AWS resources, so I updated the `get_from_tags` method to search both.
Addresses https://github.com/ManageIQ/manageiq-providers-amazon/issues/636
> Update tag name for network ports and security groups

- manageiq-providers-amazon.gemspec
aws-sdk-core v3.104.0 introduced an issue that causes metrics collection to fail with a frozen hash error.
Fixed in v3.104.3
```
[FrozenError]: can't modify frozen Hash
aws-sdk-core-3.104.0/lib/seahorse/client/plugins/request_callback.rb:67:in `delete'
aws-sdk-core-3.104.0/lib/seahorse/client/plugins/request_callback.rb:67:in `call'
aws-sdk-core-3.104.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
aws-sdk-core-3.104.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
aws-sdk-core-3.104.0/lib/seahorse/client/request.rb:72:in `send_request'
aws-sdk-cloudwatch-1.41.0/lib/aws-sdk-cloudwatch/client.rb:1658:in `get_metric_statistics'
manageiq-providers-amazon-dd5052771d9a/app/models/manageiq/providers/amazon/cloud_manager/metrics_capture.rb:178:in `block (3 levels) in …
```
> Bump aws-sdk-core to fix a frozen hash error

- app/models/manageiq/providers/amazon/cloud_manager.rb
- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
This PR also leverages the DDF.find_field method for cleaner specs.
jansa/yes? since #647 is jansa/yes?
> Prefer to not memoize at all for dynamic params

- app/models/manageiq/providers/amazon/cloud_manager.rb
The default behavior for the `async-credentials` component is [changing to be optional](https://github.com/ManageIQ/manageiq-ui-classic/pull/7347), so it has to be explicitly marked as required here.
> Make the default credentials required in the provider DDF

- app/models/manageiq/providers/amazon/cloud_manager.rb
When syncing child managers' attributes with the parent we should include the tenant_id.
> Keep the parent manager's tenant_id in sync with its child managers

- config/settings.yml
On jansa we should use the `amazon-smartstate:latest-jansa` docker image not `:latest`
Reference: https://github.com/ManageIQ/container-amazon-smartstate/pull/12#issuecomment-700686672
> [JANSA] Update the amazon smartstate docker image

- app/models/manageiq/providers/amazon/cloud_manager.rb
@agrare noticed that I forgot to add the [smartstate docker credentials endpoint](https://github.com/ManageIQ/manageiq-ui-classic/pull/2525/files) into the amazon form, probably because the old form was had a bug and it never showed these fields :confused: 
I will need some help with the validation and if it there are other fields as well...
> Add fields for smartstate docker credentials into the provider form

- app/models/manageiq/providers/amazon/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
This is an initial Cloud Volume form schema for the fields that are specific to the amazon-provided cloud volumes. I couldn't find any place where the possible types were declared, so I created a constant that now holds them.
The idea is to call this method from the API when an options request hits the `/api/cloud_volumes` endpoint with a valid `ems_id`. I am not entirely sure if the method should take the `ems_id` as an argument or I should do a lookup in the API before calling it, but this is how it works in the provider forms as well.
@miq-bot add_reviewer @agrare 
Parent issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7334
> Declared DDF schema for cloud volume creation and editing

- app/models/manageiq/providers/amazon/cloud_manager.rb
The Amazon provider was the first cloud provider to participate in the (originally) ContainerLabelTagMapping class. It has since been expanded to include many providers including Openstack, Azure, and VMware vSphere.
This means that the original labeled_resource_type of "Vm" and "Image" meaning Amazon VMs and Templates is quite confusing.
Data migration: https://github.com/ManageIQ/manageiq-schema/pull/525
UI PR: https://github.com/ManageIQ/manageiq-ui-classic/pull/7438
> Rename tag mapping categories Vm -> VmAmazon

- .rubocop_local.yml
- app/models/manageiq/providers/amazon/cloud_manager/provision/configuration.rb
- app/models/manageiq/providers/amazon/cloud_manager/provision_workflow.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm.rb
- app/models/manageiq/providers/amazon/manager_mixin.rb
This PR cleans up the last of the rubocop linter issues that I see locally. Specifically:
* The `provider_model` singleton method isn't actually private, so moves it out of the private block.
* Disables the `RescueException` warning (I don't see us changing that without risking breakage).
* Changes something that looks like a comparison (even though it isn't) in `userdata_payload` into more readable code.
* Simple whitespace fix (whitespace between method name and parens) that was causing a group expression warning.
* Disabled a specific useless assignment warning, along with a reference to why we did that.
> Fix linter issues

- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
fix specs for the refactor of vms to use ancestry, not relationships
needs
https://github.com/ManageIQ/manageiq/pull/20788 
tested here: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/283
> adjust relationship count in specs

- app/models/manageiq/providers/amazon/container_manager.rb
- app/models/manageiq/providers/amazon/container_manager/container.rb
- app/models/manageiq/providers/amazon/container_manager/container_group.rb
- app/models/manageiq/providers/amazon/container_manager/container_node.rb
- app/models/manageiq/providers/amazon/container_manager/event_catcher.rb
- app/models/manageiq/providers/amazon/container_manager/event_catcher/runner.rb
- app/models/manageiq/providers/amazon/container_manager/event_parser.rb
- app/models/manageiq/providers/amazon/container_manager/refresh_worker.rb
- app/models/manageiq/providers/amazon/container_manager/refresh_worker/runner.rb
- app/models/manageiq/providers/amazon/container_manager/refresher.rb
- app/models/manageiq/providers/amazon/inventory/collector.rb
- app/models/manageiq/providers/amazon/inventory/collector/container_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser.rb
- app/models/manageiq/providers/amazon/inventory/parser/container_manager.rb
- app/models/manageiq/providers/amazon/inventory/persister.rb
- app/models/manageiq/providers/amazon/inventory/persister/container_manager.rb
- config/settings.yml
- spec/factories/ext_management_system.rb
- spec/models/manageiq/providers/amazon/container_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/amazon/container_manager/refresher.yml
Add an `Amazon::ContainerManager` which subclasses the main `Kubernetes::ContainerManager` to support Amazon Web Service's Elastic Kubernetes Service (https://aws.amazon.com/eks/)
EKS uses STS or IAM for authentication (https://docs.aws.amazon.com/eks/latest/userguide/managing-auth.html) but after that it is a standard Kubernetes API.  This means that we simply have to add methods to acquire an STS token with a user's access_key/secret_access_key and return that as the bearer token and the base Kubernetes code takes over.
The STS tokens are valid for ~15 minutes which is sufficient for operations and the tokens stay live during a `watch` operation
In order to get an STS token you have to give the eks cluster name, I've chosen to put this in the uid_ems column rather than the name column …
> Add a basic container manager for Amazon EKS

- app/models/manageiq/providers/amazon/container_manager.rb
- spec/models/manageiq/providers/amazon/container_manager/refresher_spec.rb
While we are using a bearer token to authenticate with k8s API, we aren't storing this token in the database.  We are only storing userid and password in the authentication record, with an authtype of "bearer" this was causing the scheduled authentication_check to fail with "missing credentials" because it didn't see anything in the `:bearer` column.
https://github.com/ManageIQ/manageiq-providers-amazon/issues/682
> Fix EKS scheduled auth check returning missing creds

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/container_manager.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Because carbon has four different dropdowns, the DDF schemas need to have explicit initialValue or includeEmpty settings in order to make the form validation work.
> Adjust empty/initial values for select fields in DDF schemas

- app/models/manageiq/providers/amazon/instance_types.rb
- app/models/manageiq/providers/amazon/inventory/collector.rb
- app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
By parsing flavors using `persister.flavors.find()` we're assuming that the flavor either exists in the persister cache (aka full refresh) or already exists in the database (targeted refresh).
If someone deletes the "unknown" flavor from the database then the `persister.flavors.find("unknown")` call will return a `nil` which we're assuming can never happen in the instances parser.
> Parse flavors from the collector not the persister

- app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
> Don't override add_miq_templates to set the model_class

- app/models/manageiq/providers/amazon/manager_mixin.rb
The typical method for setting a proxy is via the `Settings.http_proxy.ec2` setting which is accessed via the `Vmdb::Utils.http_proxy_uri` method.
This is used during the instance connect/verify methods but not during the class connect/verify methods.  This leads to the inability to add an AWS provider if a proxy is required to access it.
> Use Vmdb::Utils.http_proxy_uri when adding AWS provider

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Found in: Storage->Block Storage->Volumes
Part of the Fix for: https://github.com/ManageIQ/manageiq-ui-classic/issues/7713
Adds the number value validator from Data Driven Forms to the Cloud Volume schema to ensure the user can't enter a negative number for the size field
Preview:
> Added Number Value Validator to Form Schema

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Follow-up to: https://github.com/ManageIQ/manageiq/pull/21181
This has been replaced with `supports :update`
> Remove unused validate_update_volume

- app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
This wasn't required when this was done for master because the provider_worker_mixin refactoring meant this automatically picked up the improved `all_valid_ems_in_zone` method.
Depends:
> [KASPAROV] Replace authentication_status_ok? with provider specific version

- app/models/manageiq/providers/amazon/container_manager.rb
- app/models/manageiq/providers/amazon/container_manager/container.rb
- app/models/manageiq/providers/amazon/container_manager/container_group.rb
- app/models/manageiq/providers/amazon/container_manager/container_node.rb
> Subclassed provider classes should mark the parent as a leaf class

- db/fixtures/aws_instance_types.yml
- lib/tasks_private/instance_types.rake
There used to be a rake task to auto-generate the instance_types.rb (at least as early as https://github.com/ManageIQ/manageiq-providers-amazon/pull/170)
It was removed in https://github.com/ManageIQ/manageiq-providers-amazon/pull/449 with the plan of pulling this info from the AWS API/SDK however that never materialized.
This manifested in provisioning failing because the `vpc_only` attribute was flat out incorrect for a number of flavors which caused the auto-select logic to fail.
> Add back an instance_types rake task

- app/models/manageiq/providers/amazon/cloud_manager.rb
- app/models/manageiq/providers/amazon/network_manager.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs.rb
- app/models/manageiq/providers/amazon/storage_manager/s3.rb
Match the behavior of the storage managers and dependent destroy the network_manager.  Also remove the delegation of zone to the parent manager since the zone_id is sync'd to the child managers already.  This allows us to add the `inverse_of => :parent_manager` without breaking
Dependent:
> Dependent destroy network_manager and don't delegate zone

- app/models/manageiq/providers/amazon/cloud_manager.rb
Fixed these console errors in the cloud provider form and changed implementation of hidden text-field.
@miq-bot add_reviewer @agrare 
@miq-bot add-label bug
> Fixed react prop errors for cloud_manager

- app/models/manageiq/providers/amazon/cloud_manager.rb
Add supports `:storage_manager` and function `block_storage_manager` for storage manager access on UI side: https://github.com/ManageIQ/manageiq-ui-classic/pull/7821/files
@miq-bot add_reviewer @agrare
@miq-bot add-label enhancement
> Add supports :storage_manager and block_storage_manager Function to Amazon CloudManager

- app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/collector/network_manager.rb
Only access to the EC2 service is required for the refresh to complete, other services are optional and failures there (e.g. due to lack of permissions) shouldn't cause the entire refresh to fail.
> Prevent services other than EC2 from causing refresh failures

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
These were renamed from Vm and Image to VmAmazon and ImageAmazon in the UI https://github.com/ManageIQ/manageiq-ui-classic/pull/7438 and the pluggable mapper was updated in the provider https://github.com/ManageIQ/manageiq-providers-amazon/pull/671 but the parser was never updated to match.
> Fix labeled_resource_type for Amazon Vms/Images

- spec/models/manageiq/providers/amazon/regions_spec.rb
Follow-up to https://github.com/ManageIQ/manageiq/pull/21578
> Fix regions spec after rename to from_source

- app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
- app/models/manageiq/providers/amazon/inventory/persister/definitions/network_collections.rb
- app/models/manageiq/providers/amazon/inventory/persister/definitions/storage_collections.rb
- app/models/manageiq/providers/amazon/inventory/persister/network_manager.rb
- app/models/manageiq/providers/amazon/inventory/persister/storage_manager/ebs.rb
We have added methods to core to handle setting the parent for child-managers doing combined-targeted-refresh
> Switch to standard persister definitions for multi-manager refresh

- app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb
- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
If we encounter an error collecting the stack template we shouldn't return an empty array since the `collector.stack_template()` method returns a single item not a collection.
```
[NoMethodError]: undefined method `encode' for []:Array  Method:[block (2 levels) in <class:LogProxy>]
/var/www/miq/vmdb/app/models/orchestration_template.rb:211:in `with_universal_newline'
/var/www/miq/vmdb/app/models/orchestration_template.rb:46:in `block in find_or_create_by_contents'
/var/www/miq/vmdb/app/models/orchestration_template.rb:40:in `reject'
/var/www/miq/vmdb/app/models/orchestration_template.rb:40:in `find_or_create_by_contents'
/var/www/miq/vmdb/app/models/manageiq/providers/inventory/persister/builder/cloud_manager.rb:79:in `block in orchestration_templates'
```
> Fix stack template errors causing [].encode exception

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
These unsupported_region_add calls were using `,` instead of `%` which caused `Internal Error: wrong number of arguments (given 3, expected 1..2)`
> Fix gettext interpolation syntax in unsupported_reason_add

- app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Now that this form uses the API rather than a UI controller to issue the create the param keys are coming in as strings not symbols
> Fix auth_key_pair create params

- lib/tasks_private/instance_types.rake
The ec2instances.info project no longer maintains a static instances.json file in their github repo as of https://github.com/vantage-sh/ec2instances.info/commit/d6a25fb7690b98201629e9f5b19447a08319e583
It is available at https://instances.vantage.sh/instances.json however
> The instances.json file has been removed from github

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb
part of https://github.com/ManageIQ/manageiq-api/pull/1134
move crud for cloud volume snapshots to core and use raw_ naming convention
> Cloud volume snapshot

- .github/workflows/instance_types.yaml
- .gitignore
Example run: https://github.com/agrare/manageiq-providers-amazon/actions/runs/1993106302
Example PR: https://github.com/agrare/manageiq-providers-amazon/pull/2, https://github.com/agrare/manageiq-providers-amazon/pull/5
TODO:
> Add github action to update instance-types

- .github/workflows/instance_types.yaml
When automatically updating the AWS instance types via github actions push to fork instead of the main repository
Follow-up to: https://github.com/ManageIQ/manageiq-providers-amazon/pull/752
https://github.com/ManageIQ/manageiq-providers-amazon/pull/762#issuecomment-1113657088
> AWS instance_types update push to fork

- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb
- spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Allow for auto-updating the list of aws_instance_types without having to manually edit the spec tests to update the flavors count
> Dynamically check flavors count from aws_instance_types.yml

- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Pre-requisite / companion PR to [1141](https://github.com/ManageIQ/manageiq-api/pull/1141) and [8205](https://github.com/ManageIQ/manageiq-ui-classic/pull/8205). 
Part of the process for upgrading [_attach.html.haml](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/vm_common/_attach.html.haml#L33) and [_detach.html.haml](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/views/vm_common/_detach.html.haml#L25) to react as per https://github.com/ManageIQ/manageiq-ui-classic/issues/7603.
> Add custom schema fields to Amazon attach cloud volume form

- .github/workflows/instance_types.yaml
Automatically delete the remote branch created during the automatic instance_types action
> Auto-delete instance_types branch after merge

- .github/workflows/instance_types.yaml
- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- db/fixtures/aws_database_types.yml
- lib/tasks_private/database_types.rake
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Automatically pull the latest list of rds database instance types from https://instances.vantage.sh/rds/instances.json
Also added this to the weekly cron run to update instance types
> Add a rake task to auto-update database types

- app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb
Restrict the selection of cloud_database_flavors to only active flavors.
Depends on:
> Only allow creating with active database flavors

- app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb
Related to https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/403
~~db.t1.micro is now deprecated, as seen by this error: `["status", "Error"], ["message", "Invalid DB Instance class: db.t1.micro"]` and we can see that it is no longer listed [here](https://aws.amazon.com/rds/instance-types/).~~ <- Handled in seperate PR, see discussion below.
> Updates to database schema

- spec/models/authenticator/amazon_spec.rb
https://github.com/rspec/rspec-mocks/issues 1460
> Support ruby 3: rspec-mocks 3.10.3 requires "with" to be explicit with hashes vs. kwargs

- spec/models/authenticator/amazon_spec.rb
The failure exception message now includes the requested incoming groups, changed by https://github.com/ManageIQ/manageiq/pull/22382
Fix for failing CI starting at https://github.com/ManageIQ/manageiq-providers-amazon/actions/runs/4485061610
> Fix Amazon Authenticator Spec

- lib/manageiq-providers-amazon.rb
- lib/manageiq/providers/amazon.rb
- manageiq-providers-amazon.gemspec
- spec/spec_helper.rb
https://github.com/ManageIQ/manageiq-providers-amazon/blob/a22095fd65085a052202ce707aea69839550ed87/app/models/manageiq/providers/amazon/agent_coordinator.rb#L3
ManageIQ::ApplianceConsole was pulling in this dependency for us but if zeitwerk
autoloads this provider first, the gem dependency doesn't exist yet.
See: https://github.com/ManageIQ/manageiq-appliance_console/blob/master/manageiq-appliance_console.gemspec#L32
Additionally, consolidate the gem loader to the one in the namespaced directory location.
> Add missing dependency on net-scp, consolidate gem loader to the namespaced location

- spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
> Include shared EMS#pause!,#resume! specs

- spec/models/manageiq/providers/amazon/regions_spec.rb
The regions spec has a hard-coded list of "atypical regions" which really just means regions which exist but are not available to us via the aws-sdk `describe_regions` API call.
It would be simpler to just check that all of the regions that we do have access to are in the regions list.  This would allow us to update the `config/regions.yml` list in an automated way.
> Refactor regions spec to not hard-code atypical regions

- app/models/manageiq/providers/amazon/cloud_manager/orchestration_template.rb
Part of https://github.com/ManageIQ/manageiq/issues/22696
Keep compatibility with psych 3.1+ since permitted_classes and aliases were added as keyword arguments to safe_load.
Note, psych 4 changed the interface to drop support with positional arguments for the permitted_classes. Now, we must explicitly specify them using kwargs.
> Update safe_load calls to work with psych 3/4

- .github/workflows/instance_types.yaml
@agrare Please review.  Note that Ruby 2.7 is actually failing to bundle install at all.  See https://github.com/ManageIQ/manageiq-providers-amazon/actions/runs/7770305058/job/21329461130
> Bump Ruby version for instance_types GitHub action

- app/models/manageiq/providers/amazon/cloud_manager/template.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm/operations.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm/operations/guest.rb
- app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
- app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_object.rb
- spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
dropped references to `supports_provisioning?` and `supports_control?`
blocked on:
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Deprecating `unsupported_reason_add`. Returning the string instead
Note, these are all the same:
```ruby
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports_feature2?
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports?(:feature2)
unsupported_reason(:feature2) unless supports?(:feature2)
unsupported_reason(:feature2)
```
> Drop supports_feature? and unsupported_reason_add

- manageiq-providers-amazon.gemspec
Related https://github.com/ManageIQ/manageiq-appliance_console/pull/248
We'll need to merge this when we go to bump the appliance_console gem in the core Gemfile
> Bump net-scp gem for openssl 3.0 support

- app/models/manageiq/providers/amazon/agent_coordinator.rb
require net/scp seems to be around 5 MB of memory and requires 122 files:
`  0  <+  net/scp (0.236512) (5308416) (122)`
If we ever are to eager load plugins, we need to avoid having them requiring client code at code load time.
> Delay load the net-scp require to avoid bloating eager loading

- db/fixtures/aws_database_types.yml
- lib/tasks_private/database_types.rake
Handle case where deprecated AWS database types have a nil `networkPerformance` key
@miq-bot add_reviewer @agrare
> Handle nil case for networkPerformance key in deprecated AWS database types

- db/fixtures/aws_database_types.yml
- lib/tasks_private/database_types.rake
We were handling `Gigabit` in network_performance values but not properly handling cases where `Gbps` is used
@miq-bot add_reviewer @agrare
> Handle Gbps in AWS database types

- app/models/manageiq/providers/amazon/network_manager.rb
- app/models/manageiq/providers/amazon/storage_manager/ebs.rb
- config/settings.yml
Refreshes should be done via the cloud manager. Instance methods are already delegated however the class level refresh methods were not delegated.
Following changes in https://github.com/ManageIQ/manageiq-providers-azure/pull/564
@miq-bot add_reviewer @agrare
> Delegate refresh_ems class method to parent cloud manager

- .github/workflows/instance_types.yaml
Since the core repo has now upgraded to no longer support Ruby 3.0, this
now fails on Ruby 3.0 with
Your Ruby version is 3.0.7, but your Gemfile specified >= 3.1.1, < 3.5.0
This commit upgrades the Ruby version to 3.3 to fix this.
@agrare Please review.
> Update instance_types action to Ruby 3.3

- app/models/manageiq/providers/amazon/network_manager.rb
The Amazon NetworkManager doesn't run an EventCatcher so there is no need for a `.default_blacklisted_event_names` method.  This was a copy&paste from the `CloudManager` and not specific to network-type events.
https://github.com/ManageIQ/manageiq/issues/19707
> Drop unused default_blacklisted_events from NetworkManager

- app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
- spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
TODO: This is to get some discussion on possible causes.  I'm not sure why rails 7.1 seems to be changing the persistance of the API results from aws-sdk.
support_url, support_email, and support_description don't exist in the response payload in the cassette for these tests, while others have it, and yet previously, these unset fields were set as nil with rails 7.0.  It's unclear what changed with rails 7.1 but now these nil value fields aren't persisted in the extra column, so I had to remove them in the tests where these values in the cassettes didn't exist in the response.
collector/cloud_manager.rb:
```ruby
def service_offerings
aws_service_catalog.client.search_products_as_admin.product_view_details
...
end
```
parser/cloud_manager.rb:
```ruby
collector.service_offerings.each do …
```
> With rails 7.1, these nil values are not persisted

- spec/models/authenticator/amazon_spec.rb
Introduced by https://github.com/aws/aws-sdk-ruby/pull/3204 in v3.220.1
> Fix missing required params in AWS auth stubs

- app/models/manageiq/providers/amazon/agent_coordinator.rb
This PR addresses three critical issues in the AWS Agent Coordinator that prevent Smart State Analysis from working correctly.
**Problem**: The [find_or_create_keypair](https://github.com/ManageIQ/manageiq-providers-amazon/blob/5f946e81d3a7c8d793eb4f1b7ad8b1c1110bc7a8/app/models/manageiq/providers/amazon/agent_coordinator.rb#L414) method passes a `:name` symbol key, but [raw_create_key_pair](https://github.com/ManageIQ/manageiq-providers-amazon/blob/5f946e81d3a7c8d793eb4f1b7ad8b1c1110bc7a8/app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb#L8) expects a string key `"name"`, causing keypair creation to fail with "missing required parameter params[:key_name]".
**Root Cause**: This was introduced by PR #750 which changed the API to use string keys instead of symbols for JSON …
> Fix SSA issues in AWS: keypair param, IAM role check, route table logic

- app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
```
pp subnet
{"availability_zone_id"=>"usw2-az2",
"map_customer_owned_ip_on_launch"=>false,
"owner_id"=>"006216435641",
"assign_ipv_6_address_on_creation"=>true,
"ipv_6_cidr_block_association_set"=>
[{"association_id"=>"subnet-cidr-assoc-0f62df830a93264f2",
"ipv_6_cidr_block"=>"2600:1f14:1895:4800::/56",
"ipv_6_cidr_block_state"=>{"state"=>"associated"},
"ipv_6_address_attribute"=>"public",
"ip_source"=>"amazon"}],
"tags"=>[{"key"=>"Name", "value"=>"achan-ipv6-subnet"}],
"subnet_arn"=>"arn:aws:ec2:us-west-2:006216435641:subnet/subnet-09468a3d3254b13ce",
"enable_dns_64"=>false,
"ipv_6_native"=>true,
"private_dns_name_options_on_launch"=>{"hostname_type"=>"resource-name", "enable_resource_name_dns_a_record"=>false, "enable_resource_name_dns_aaaa_record"=>true}, …
```
> Support IPv6 only Subnets
