app/models/manageiq/providers/amazon/cloud_manager.rb, app/models/manageiq/providers/amazon/cloud_manager/virtual_template.rb
contains the relevant changes from https://github.com/ManageIQ/manageiq/pull/9492
which got merged after we created the providers-amazon repo
@jntullo can you double check that this is the only change to the amazon provider?
@Fryguy pls merge
=> Virtual Templates API

bin/setup, tools/ci/before_install.sh
once https://github.com/ManageIQ/manageiq/pull/9314 is merged we can point the setup scripts to ManageIQ repo
=> point setup files to manageiq repo

app/models/manageiq/providers/amazon/cloud_manager/virtual_template.rb
Minor update to the amazon virtual template to account for required parameters
=> Required Virtual Template Parameters

spec/spec_helper.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml
fixes https://github.com/ManageIQ/manageiq-providers-amazon/issues/2
@Fryguy review?
=> move vcr cassettes for amazon from manageiq repo over

spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
into spec file and remove the factory altogether
fixes CI build failures introduced by https://github.com/ManageIQ/manageiq/pull/7050
@miq-bot add_labels bug,test
@blomquisg review and merge?
=> move creation of amazon cloudmanager with different authentication

app/models/manageiq/providers/amazon/cloud_manager/provision/configuration.rb, spec/models/manageiq/providers/amazon/cloud_manager/provision/configuration_spec.rb
This PR and https://github.com/ManageIQ/manageiq/pull/9800 are co-dependent, we can re-run the tests once 9800 is merged to get the tests passing.
https://bugzilla.redhat.com/show_bug.cgi?id=1355895
=> Ensure user_data is Base64 encoded

app/models/manageiq/providers/amazon/cloud_manager.rb
corresponding PR https://github.com/ManageIQ/manageiq/pull/9880
@chessbyte pls merge this too?
=> refactor validate_regions to supports_regions

app/models/manageiq/providers/amazon/network_manager.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer_health_check.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer_listener.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer_pool.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer_pool_member.rb, app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml
LBaaS (Load Balancer as a Service) for Amazon. Patch contains STI models, refresh parser, specs and VCRs containing new HTTP communication
=> Amazon elb refresh

app/models/manageiq/providers/amazon/cloud_manager/template.rb
Changes to address https://github.com/ManageIQ/manageiq/pull/10561#discussion_r75485697
https://bugzilla.redhat.com/show_bug.cgi?id=1344079
https://bugzilla.redhat.com/show_bug.cgi?id=1347278
@durandom, please review, these are changes to support Template provisioning in Amazon, related to changes in https://github.com/ManageIQ/manageiq/pull/10651
=> Added supports_provisioning?  support for Amazon Template

app/models/manageiq/providers/amazon/cloud_manager/vm.rb, app/models/manageiq/providers/amazon/network_manager.rb, app/models/manageiq/providers/amazon/network_manager/security_group.rb
Move NetworkManager code to base classes
=> Move NetworkManager code to base classes

README.md
dont repeat the info on how to work on this provider here, but point to our master guides
@blomquisg review and merge?
=> add link to developer setup in manageiq

app/models/manageiq/providers/amazon/regions.rb
addresses https://bugzilla.redhat.com/show_bug.cgi?id=1346065
=> removed gov cloud from list of regions

app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml
The collection of the public IP addresses were broken and we were not collecting private addresses for the old ec2 instances.
Fixes Issue:
https://github.com/ManageIQ/manageiq/issues/10586
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1371204
=> Fix collection of public ip addresses

zanata.xml
This is a config file for upload / download of gettext catalogs from `translate.zanata.org`
=> Add zanata.xml

spec/controllers/cloud_network_controller_spec.rb, spec/controllers/cloud_subnet_controller_spec.rb, spec/controllers/ems_network_controller_spec.rb, spec/controllers/floating_ip_controller_spec.rb, spec/controllers/load_balancer_controller_spec.rb, spec/controllers/network_port_controller_spec.rb, spec/controllers/network_router_controller_spec.rb, spec/controllers/security_group_controller_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb, tools/ci/before_install.sh
=> [wip] EmsNetwork controller specs

app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb
Change load balancer and instance port to range
=> Change load balancer and instance port to range

spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb
fix broken CI by doing the same renaming as in https://github.com/ManageIQ/manageiq/pull/11287
cc @bdunne 
@jrafanie can you merge this as well?
=> include namespaced workflow helper

app/models/manageiq/providers/amazon/cloud_manager/vm/operations.rb, app/models/manageiq/providers/amazon/cloud_manager/vm/operations/guest.rb
continue work done in https://github.com/ManageIQ/manageiq/pull/11075 here
makes CI :green_heart: again
=> refactor validate_reboot_guest to supports :reboot_guest

bin/setup, tools/ci/before_install.sh
ci should run against miq euwe too
probably we can automagically discover what branch we are running on and use that.
but as we dont really want to use miq naming in here, I think explicitily setting it is fine
=> [EUWE] point euwe branch to manageiq euwe branch

app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb
in case the image does not exist in miq, like we dont import
public images but the instance was started from a public image, which
can only happen if you start the instance outside of miq.
then before the hardware would still be added to the vm, but without
the `_type` fields mentioned above
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1378039
=> get virtualization_type and root_device_type from instance

app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb
Depends on https://github.com/ManageIQ/manageiq-providers-amazon/pull/36 and https://github.com/ManageIQ/manageiq/pull/10866
=> Fix collection of secordary fixed ip per eni

app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, app/models/manageiq/providers/amazon/network_manager/refresh_parser_dto.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml
Fetch cloud subnets as a top level entity
Depends on: https://github.com/ManageIQ/manageiq/pull/12020
=> Fetch cloud subnets as a top level entity

spec/models/manageiq/providers/amazon/aws_stubs.rb, spec/tools/refresh_performance/aws_refresh_performance.rb
Advanced performace specs. We want to measure create, update and
delete for all refresh configurations we support.
=> Advanced performace specs

app/models/manageiq/providers/amazon/regions.rb, spec/models/manageiq/providers/amazon/regions_spec.rb
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1346065
this needs settings.yml in gems to be merged first
=> added ability to disable regions at runtime

app/models/manageiq/providers/amazon/network_manager.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer.rb, app/models/manageiq/providers/amazon/network_manager/load_balancer_service_option_converter.rb
Add amazon load balancer actions
=> Add amazon load balancer actions

app/models/manageiq/providers/amazon/cloud_manager/vm/operations/power.rb
continue refactoring started in this PR 
https://github.com/ManageIQ/manageiq/pull/11752/
=> refactor validate_suspend to supports syntax

.codeclimate.yml, .rubocop_base.yml, .rubocop_cc.yml
=> Allow code climate

spec/models/manageiq/providers/amazon/aws_stubs.rb, spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb
We need to test also if we are deleting the data  correctly, if api does not return them anymore
Depends on:
https://github.com/ManageIQ/manageiq-providers-amazon/pull/60
https://github.com/ManageIQ/manageiq/pull/12021
https://github.com/ManageIQ/manageiq/pull/12020
=> Stubbed specs for aws network manager test deleting

app/models/manageiq/providers/amazon/network_manager/refresh_parser_dto.rb
Collect all fixed interfaces in dto refresh
=> Collect all fixed interfaces in dto refresh

app/models/manageiq/providers/amazon/network_manager/refresh_parser_dto.rb
Link to the db using local_db_cache_all strategy
=> Link to the db using local_db_cache_all strategy

app/models/manageiq/providers/amazon/cloud_manager/refresh_parser_dto.rb, app/models/manageiq/providers/amazon/cloud_manager/refresher.rb
Amazon CloudManager DTO refresh
=> Amazon CloudManager DTO refresh

spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
the latter one was removed from manageiq core and wasnt really needed
This one removed it
https://github.com/ManageIQ/manageiq/pull/12419
=> use vm_amazon instead of vm_perf_amazon

app/models/manageiq/providers/amazon/cloud_manager/refresh_parser_dto.rb, app/models/manageiq/providers/amazon/network_manager/refresh_parser_dto.rb, spec/models/manageiq/providers/amazon/aws_stubs.rb, spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb
Stubbed specs for dto and non dto for Amazon. Also fixing a CI due to recent DTO changes in MIQ
=> Stubbed amazon managers spec and fixing ci

spec/tools/refresh_performance/aws_refresh_performance_cloud_manager.rb, spec/tools/refresh_performance/aws_refresh_performance_network_manager.rb
Updated network and cloud manager refresh benchmarks
=> Updated network and cloud manager refresh benchmarks

spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Add CloudManager Stubbed Specs
=> Add CloudManager Stubbed Specs

config/initializers/descendant_loader.rb
no need for adding this since this is in manageiq
https://github.com/ManageIQ/manageiq/pull/12221/commits/83300fbfa871afc08343daeb959299b9a52e4887
=> remove descendant loader config

.codeclimate.yml, .rubocop.yml, .rubocop_cc.yml, .travis.yml, Gemfile, README.md, bin/setup, bin/update, manageiq-providers-amazon.gemspec, spec/controllers/cloud_network_controller_spec.rb, spec/controllers/cloud_subnet_controller_spec.rb, spec/controllers/ems_network_controller_spec.rb, spec/controllers/floating_ip_controller_spec.rb, spec/controllers/load_balancer_controller_spec.rb, spec/controllers/network_port_controller_spec.rb, spec/controllers/network_router_controller_spec.rb, spec/controllers/security_group_controller_spec.rb
* leverage ManageIQ::Environment for setup
* dev dependencies in gemspec
* rubocop definition from managiq/guides
=> applying changes from provider generator

README.md, manageiq-providers-amazon.gemspec
as requested per https://github.com/ManageIQ/manageiq-providers-amazon/pull/97
generator PR https://github.com/ManageIQ/manageiq/pull/13382
=> License and dev dependencies

Gemfile, manageiq-providers-amazon.gemspec, spec/spec_helper.rb
backported from master
fixes #103
=> [EUWE] fix codeclimate to make CI pass again

app/models/manageiq/providers/amazon/cloud_manager/refresh_parser_inventory_object.rb
We need to pass true to mark public images
=> We need to pass true to mark public images

app/models/manageiq/providers/amazon/regions.rb
Add Canada (Central) Region
see announcement 
https://aws.amazon.com/about-aws/whats-new/2016/12/announcing-the-aws-canada-central-region/
https://bugzilla.redhat.com/show_bug.cgi?id=1414609
need an darga and euwe bz
=> add ca-central region

CHANGELOG.md
First pass at changelog for this repository
[skip ci]
=> Changelog 52

CHANGELOG.md
fix links to use this repo
[skip ci]
=> Fix links for changelog

app/models/manageiq/providers/amazon/builder.rb, app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb, app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
Move parsers under Inventory::Parser
=> Move parsers under Inventory::Parser

app/models/manageiq/providers/amazon/inventory.rb, app/models/manageiq/providers/amazon/inventory/collector.rb, app/models/manageiq/providers/amazon/inventory/parser.rb
Filing autoload for parsers, need a manual require
=> Failing autoload for parsers

app/models/manageiq/providers/amazon/cloud_manager.rb, app/models/manageiq/providers/amazon/cloud_manager/cloud_volume.rb, app/models/manageiq/providers/amazon/cloud_manager/cloud_volume_snapshot.rb, app/models/manageiq/providers/amazon/storage_manager/ebs.rb
Cleanup StorageManager STI classes to avoid warnings in log
=> Cleanup StorageManager STI classes to avoid warnings in log

app/models/manageiq/providers/amazon/cloud_manager/event_catcher/stream.rb, app/models/manageiq/providers/amazon/cloud_manager/event_parser.rb, spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/AWS_ALARM_awselb-EmSRefreshSpecVPCELB-Unhealthy-Hosts.json, spec/models/manageiq/providers/amazon/cloud_manager/event_parser_spec.rb
Catch cloudwatch alarm events + specs
=> Catch cloudwatch alarms

app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
=> Renamed refresh strategies

spec/factories/ext_management_system.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_inventory_object_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_other_region_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb, spec/models/manageiq/providers/amazon/regions_spec.rb
Use secrets for VCR based specs
=> Use secrets for VCR based specs

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb
Filter terminated instance properly, including all inferred
records.
=> Filter terminated instance properly

spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Depends on: 
Extend aws ebs specs with specs for cloud_volumes and cloud_volumes_snapshots.
=> Extend aws ebs specs

app/models/manageiq/providers/amazon/inventory/hash_collection.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_other_region_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml
Depends on:
Using new counts mixin to compare DB counts to war API data counts. This way is more accurate than comparing to fixed numbers and doesn't require constant changes when re-record the VCR.
=> Refactoring of counts specs

app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_wiht_floating_ip_and_lbs_full_refresh.yml
Add spec for targeted refresh of vpc VM with floating IP and LBs
=> Add spec for targeted refresh of vpc vm with floating ip and lbs

spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/aws_stubs.rb, spec/models/manageiq/providers/amazon/cloud_manager/event_parser_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/orchestration_service_option_converter_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/provision/configuration_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/provision_workflow_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager_spec.rb, spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/amazon/storage_manager/ebs/stubbed_refresher_spec.rb
Rubocop -a for all Amazon specs
=> Rubocop -a for all Amazon specs

app/models/manageiq/providers/amazon/inventory/collector/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb, app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_floating_ip_and_lbs_full_refresh.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_public_ip_and_template.yml
Fetch all referenced templates regardless of what we allow for collection. Meaning the template relation of a VM and therefore a VM's operating system name should never be blank. 
Implements:
https://www.pivotaltracker.com/story/show/142318659
=> Fetch all referenced templates regardles of what we allow for collection

app/models/manageiq/providers/amazon/cloud_manager/refresher.rb, config/settings.yml, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_other_region_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
Add options for graph refresh, by default graph refresh is switched off
=> Add options for graph refresh

spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/ec2_classic_vm_and_lb_full_refresh.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_floating_ip_and_lbs_full_refresh.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_public_ip_and_template.yml
Fix and enhance cloudformations specs for aws
=> Fix and enhance cloudformations specs for aws

spec/tools/refresh_performance/aws_refresh_performance_cloud_manager.rb, spec/tools/refresh_performance/aws_refresh_performance_network_manager.rb
=> Fix perf scripts

app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb
Rename $aws_log to _log since _log is not available
=> Rename $aws_log to _log since _log is not available

app/models/manageiq/providers/amazon/inventory/collector/storage_manager/s3.rb, app/models/manageiq/providers/amazon/storage_manager/s3/refresh_parser.rb, spec/models/manageiq/providers/amazon/storage_manager/s3/stubbed_refresher_spec.rb
Use $aws_log instead of _log, since _log is not included
=> Use $aws_log instead of _log

CHANGELOG.md
Sprint 57 - 27 PRs
Sprint 58 - 4 PRs
[skip ci]
=> Changelogs Sprints 57 AND 58

app/models/manageiq/providers/amazon/cloud_manager/provision/cloning.rb
Part of [Refactor MiqRequestTask::Dumping. #14547](https://github.com/ManageIQ/manageiq/pull/14547).
@miq-bot assign @gmcculloug 
@miq-bot add_label fine/yes, euwe/no
=> Rename dumpObj to dump_obj for MiqRequestTask.

CHANGELOG.md
=> Fine Changelog Consolidation

app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb, app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stack.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested_with_vm.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_floating_ip_and_lbs_full_refresh.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/vpc_vm_with_public_ip_and_template.yml
Targeted refresh specs for orchestration stacks, fixing few bugs made visible by the specs.
=> Targeted refresh specs for orchestration stacks

app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/cloud_volume_with_snapshot.yml
Depends on:
Targeted refresh specs for cloud volumes and fixes discovered doing the spec
=> Targeted refresh specs for cloud volumes

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
Rewrite parsing of flavors, keypairs and azs to the new syntax
=> Rewrite parsing of flavors, keypairs and azs to the new syntax

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
Depends on:
Rewrite images parser to the new syntax
=> Rewrite images parser to the new syntax

spec/models/manageiq/providers/amazon/aws_stubs.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Enhance stubbed specs with testing tags
=> Enhance stubbed specs with testing tags

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stack.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested_with_vm.yml
Rewrite stacks parser to the new syntax + new VCRs since the order of API requests has changed
=> Rewrite stacks parser to the new syntax

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/cloud_manager.rb
Rewrite the instance parser to the new syntax
=> Rewrite the instance parser to the new syntax

app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb, app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
Rewrite S3 parser to a new format
=> Rewrite S3 parser to a new format

app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb, app/models/manageiq/providers/amazon/inventory_collection_default/storage_manager.rb
Rewrite EBS parser to a new format
=> Rewrite EBS parser to a new format

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
Rewrite network and subnet parser to a new format
=> Rewrite network and subnet parser to a new format

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
Rewrite sec groups and firewall rules parser to a new format
=> Rewrite sec groups and firewall rules parser to a new format

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
Rewrite load balancers parser to a new format
=> Rewrite load balancers parser to a new format

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb
Depends on:
Rewrite network ports and floating ips parser to a new format
=> Rewrite network ports and floating ips parser to a new format

CHANGELOG.md
Update RC-2 to Beta-2
[skip ci]
=> Changelog 59 Fine Beta-2

CHANGELOG.md
Update rc-2 to beta-2
[skip ci]
=> [FINE] Changelog for Beta-2 release

app/models/manageiq/providers/amazon/inventory/parser.rb, app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
Depends on:
Cleanup parser helpers
=> Cleanup parser helpers

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
Depends on:
Cleanup network manager parser
=> Cleanup network manager parser

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Depends on:
Cleanup cloud manager parser
=> Cleanup cloud manager parser

app/models/manageiq/providers/amazon/inventory/parser/storage_manager/ebs.rb, app/models/manageiq/providers/amazon/inventory/parser/storage_manager/s3.rb
Depends on:
Cleanup storage managers parsers
=> Cleanup storage managers parsers

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb, app/models/manageiq/providers/amazon/inventory_collection_default/network_manager.rb, app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb, spec/models/manageiq/providers/amazon/network_manager/stubbed_refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_inventory_object.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_other_region.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stack.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested.yml, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/refresher_targeted/orchestration_stacks_nested_with_vm.yml
Refresh port and floating ip for a LB(both old and new refresh) + specs and new VCRs
Related to BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1387616
=> Refresh port and floating ip for a lb

config/settings.yml
Add CloudWatch events for VM to a timeline
=> Add CloudWatch events for VM to a timeline

CHANGELOG.md
=> Changelog Sprint 60

.rspec, .rspec_ci, README.md, Rakefile, lib/tasks/README.md, lib/tasks/amazon.rake, lib/tasks_private/spec.rake, manageiq-providers-amazon.gemspec, spec/spec_helper.rb
ran the generator again with
```bash
bundle exec rails g provider amazon --path ../
```
these are the changes.
cc @bdunne
=> run provider generator to sync changes from core

app/models/manageiq/providers/amazon/regions.rb
Refactor the regions_by_hostname method to be simpler.
=> Refactor the regions_by_hostname method to be simpler.

.travis.yml
was pointing to main room
@Fryguy pls merge
=> point travis webhook to amazon gitter room

app/models/manageiq/providers/amazon/cloud_manager.rb, app/models/manageiq/providers/amazon/cloud_manager/orchestration_template.rb, spec/models/manageiq/providers/amazon/cloud_manager/orchestration_template_spec.rb
Prepare to move OrchestrationTemplate to each provider.
This is a step before the migration.
https://bugzilla.redhat.com/show_bug.cgi?id=1417021
=> Move OrchestrationTemplateCfn to manageiq-providers-amazon

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
=> Add nil checks for stack

CHANGELOG.md
Added Fine-3 section
Removed PRs from Unreleased sections that were part of Fine-3
[skip ci]
=> Changelog Rollups for Fine-3

app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb, spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/AWS_API_CALL_CreateKeyPair.json, spec/models/manageiq/providers/amazon/cloud_manager/event_catcher/cloud_watch/AWS_API_CALL_DeleteKeyPair.json, spec/models/manageiq/providers/amazon/cloud_manager/event_target_parser_spec.rb
Correctly parse key pair reference + specs
=> Correctly parse key pair reference

app/models/manageiq/providers/amazon/cloud_manager/refresher.rb
=> Use the base refresher's save_inventory method

app/models/manageiq/providers/amazon/cloud_manager/refresher.rb, app/models/manageiq/providers/amazon/network_manager/refresher.rb, app/models/manageiq/providers/amazon/storage_manager/ebs/refresher.rb, app/models/manageiq/providers/amazon/storage_manager/s3/refresher.rb
Depends on:
Cleanup refreshers using base class refresher for ManagerRefresh
=> Cleanup refreshers using base class refresher for ManagerRefresh

app/models/manageiq/providers/amazon/agent_coordinator.rb
=> Raise the intended message

app/models/manageiq/providers/amazon/agent_coordinator.rb
=> Unpriveleged user can't docker login

app/models/manageiq/providers/amazon/agent_coordinator.rb, app/models/manageiq/providers/amazon/agent_coordinator_worker/runner/response_thread.rb
@roliveri Please review.  This commit was somehow missed during last week's PR.
=> Add ssa_queue public method to the coordinator

app/models/manageiq/providers/amazon/agent_coordinator.rb
In log messages, replace all 'SSA' with 'smartstate'.
=> Replace SSA with smartstate in log messages

config/settings.yml
Depends on:
Turn on batch saving by default
=> Turn on batch saving by default

app/models/manageiq/providers/amazon/agent_coordinator.rb
Both registry and image are needed for docker to pull image from private docker repos.
=> Combine registry and image together when registry needs.

CHANGELOG.md
=> [GAPRINDASHVILI] Update changelog for gaprindashvili beta1

app/models/manageiq/providers/amazon/agent_coordinator.rb
No need to make two separate calls
=> perform_commands accepts an array of commands

app/models/manageiq/providers/amazon/agent_coordinator.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1512676
=> Fix no security group exists at the first time

app/models/manageiq/providers/amazon/agent_coordinator_worker/runner.rb, app/models/manageiq/providers/amazon/agent_coordinator_worker/runner/response_thread.rb
At the time of the initial implementation of the
AgentCoordinatorWorker::Runner::ResponseThread several suggestions were made
post-merge by @fryguy that are being looked at now.
Those comments may be found here: https://github.com/ManageIQ/manageiq-providers-amazon/pull/319.
I am omitting the code to restart the thread if it dies at this point and will include it under a separate PR.  Some other comments were included in the original PR.
Those included here are:
1) Change the require of xml_utils for consistency.
2) Protect access to the @coordinators list with a Mutex.  Since the Runner
modifies this list every so often while the ResponseThread reads from it
between processing responses and sleeping the ResponseThread will lock all
access to the list while not sleeping.  The Runner will …
=> Suggested Changes from Initial Implementation

app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Fix KeyPair create and import actions
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1513515
=> Fix KeyPair create and import actions

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb, app/models/manageiq/providers/amazon/network_manager/refresh_parser.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Correct status for network, we were comparing with wrong value
Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1518687
=> Correct status for network

app/models/manageiq/providers/amazon/cloud_manager.rb, spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
Sets the catalog type for Amazon EMS instance
Needed for PR https://github.com/ManageIQ/manageiq/pull/16559
=> Added supported_catalog_types

app/models/manageiq/providers/amazon/agent_coordinator.rb
=> Add cleanup logic to remove zombie instance in unexpected cases

app/models/manageiq/providers/amazon/agent_coordinator.rb, app/models/manageiq/providers/amazon/agent_coordinator_worker/runner.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1527620
=> Fixes to cleanup agents if AgentCoordinatorWorker is restarted.

app/models/manageiq/providers/amazon/agent_coordinator.rb, app/models/manageiq/providers/amazon/agent_coordinator_worker/runner/response_thread.rb, app/models/manageiq/providers/amazon/cloud_manager/refresh_parser.rb, app/models/manageiq/providers/amazon/cloud_manager/vm_or_template_shared/scanning.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresh_parser_spec.rb
https://github.com/ManageIQ/manageiq-providers-amazon/issues/388
=> Fixes to send job defined scanning categories in request message

locale/fr/ManageIQ_Providers_Amazon.po
This PR contains final translation fixes / polishing for Gaprindashvili GA.
=> [GAPRINDASHVILI] Final translations for gaprindashvili

config/settings.yml
This fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1537165
=> Moved AWS_API_CALL_TerminateInstances from addition to deletion category

app/models/manageiq/providers/amazon/inventory/parser/network_manager.rb
Depends on:
We had missing keys for manager_ref of firewally_rules and
we are changing the way to access the primary_index.
=> Fix network_parser after the indexes refactoring

app/models/manageiq/providers/amazon/agent_coordinator.rb
https://github.com/ManageIQ/manageiq-providers-amazon/issues/404
=> Raise exceptions if SSH command fail

spec/models/manager_refresh/inventory_collection_default_spec.rb, spec/vcr_cassettes/manager_refresh/inventory_collection_default.yml
this is a followup to https://github.com/ManageIQ/manageiq/pull/16886
=> test inventory reconnection

config/settings.yml
Fixes BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1537520
=> Added instance update event handling

app/models/manageiq/providers/amazon/agent_coordinator.rb
https://bugzilla.redhat.com/show_bug.cgi?id=1557377
=> Fixes VPC selection to make sure it has internet gateway attached.

app/models/manageiq/providers/amazon/regions.rb, db/fixtures/aws_regions.yml, lib/tasks_private/regions.rake, spec/models/manageiq/providers/amazon/cloud_manager_spec.rb, spec/models/manageiq/providers/amazon/regions_spec.rb
=> load regions list from aws-sdk gem's source

app/models/manageiq/providers/amazon/cloud_manager/flavor.rb
This is pluggable version of https://github.com/ManageIQ/manageiq/pull/16944
=> Add display name for flavor

app/models/manageiq/providers/amazon/agent_coordinator.rb
For the safety reason, use awesome spawn builder to create command line.
=> Use AwesomeSpawn to build command line

app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb, app/models/manageiq/providers/amazon/inventory/persister/definitions/storage_collections.rb, app/models/manageiq/providers/amazon/inventory/persister/network_manager.rb
Optimizations and simplification of InventoryCollection definitions
**Issue**: https://github.com/ManageIQ/manageiq/issues/17396
- ((**depends on**): https://github.com/ManageIQ/manageiq/pull/17621
What is possible is moved to core
=> Persister: optimized InventoryCollection definitions

app/models/authenticator/amazon.rb
=> Link to IAM docs was in German, and not English

app/models/manageiq/providers/amazon/cloud_manager/event_target_parser.rb, app/models/manageiq/providers/amazon/cloud_manager/refresher.rb, app/models/manageiq/providers/amazon/inventory.rb, app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_snapshot.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_spec.rb
Move ManagerRefresh to InventoryRefresh
Depends on:
=> Move ManagerRefresh to InventoryRefresh

app/models/manageiq/providers/amazon/agent_coordinator.rb
Add clear error information for the unqualified VPCs.
https://bugzilla.redhat.com/show_bug.cgi?id=1654511
=> Clarify the error information for VPC selection

spec/factories/cloud_volume.rb, spec/factories/ext_management_system.rb, spec/factories/orchestration_template.rb
FactoryBot 5.0 will remove static attributes, replacing with dynamic
=> Removal of static attributes in factories

db/fixtures/aws_instance_types.yml, db/fixtures/aws_regions.yml, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/amazon/regions_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/regions.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1670793
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1644799
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1647845
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653780
=> update instance types and regions

app/models/manageiq/providers/amazon/agent_coordinator.rb
Use safe navigation operator to avoid nil exception.
https://bugzilla.redhat.com/show_bug.cgi?id=1678564
=> Add checking on route before retrieving its gateway_id

app/models/manageiq/providers/amazon/manager_mixin.rb, spec/models/authenticator/amazon_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
@agrare @jrafanie Please review.
=> Remove references to MiqPassword

app/models/manageiq/providers/amazon/cloud_manager/metrics_capture.rb, spec/models/manageiq/providers/amazon/cloud_manager/metrics_capture_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/cloud_manager/metrics_capture-win2016.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1684525
Gather data with the new metric names from CloudWatch Agent
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html
=> collect metrics from CloudWatch Agent

app/models/manageiq/providers/amazon/regions.rb, config/settings.yml, db/fixtures/aws_instance_types.yml, db/fixtures/aws_regions.yml, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/amazon/regions_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/regions.yml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1705565
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703474
=> new regions and instance types

lib/manageiq/providers/amazon/engine.rb
Change plugin common methods to class methods
=> Change plugin common methods to class methods

config/settings.yml
From @Fryguy:
> I don't think we disable anything upstream, so we can let the community try it.
From @simaishi:
> We'll be enabling all regions for upstream and disabling untested regions for downstream.
=> undisable all regions

spec/models/manageiq/providers/amazon/cloud_manager/refresh_worker_spec.rb
https://github.com/ManageIQ/manageiq/pull/18842 just got merged which changes all emses in tests to be leaf classes, since we should only be testing leaf classes irl.
=> Fixing spec for emses

db/fixtures/aws_instance_types.yml, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724686
https://aws.amazon.com/blogs/aws/new-the-next-generation-i3en-of-i-o-optimized-ec2-instances/
https://aws.amazon.com/blogs/aws/now-available-new-c5-instance-sizes-and-bare-metal-instances/
https://aws.amazon.com/blogs/aws/ec2-instance-update-two-more-sizes-of-m5-r5-instances/
=> new instance types

db/fixtures/aws_regions.yml
Fixes BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1737459
=> Added Middle East Bahrain region

lib/tasks_private/regions.rake
This rake task now just updates the regions yaml file.
=> We no longer disable regions in the settings

db/fixtures/aws_instance_types.yml, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724686
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724631
=> add metal to names and remove dedicated

spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/refresher_inventory_object_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
This fixes the flavor counts in AWS specs
=> [IVANCHUK] Fix AWS flavor counts in specs

manageiq-providers-amazon.gemspec
@agrare Please review.
Should be merged along with:
- https://github.com/ManageIQ/manageiq/pull/19436
- https://github.com/ManageIQ/manageiq-gems-pending/pull/451
=> Reduce the number of gems for AWS SDK usage

app/models/manageiq/providers/amazon/agent_coordinator_worker.rb, app/models/manageiq/providers/amazon/network_manager/event_catcher.rb, app/models/manageiq/providers/amazon/network_manager/metrics_collector_worker.rb, app/models/manageiq/providers/amazon/network_manager/refresh_worker.rb, app/models/manageiq/providers/amazon/storage_manager/ebs/refresh_worker.rb, app/models/manageiq/providers/amazon/storage_manager/s3/refresh_worker.rb, spec/models/manageiq/providers/amazon/agent_coordinator_worker_spec.rb
Requires https://github.com/ManageIQ/manageiq/pull/19516
=> Rely on the default implementation of .ems_class

app/models/manageiq/providers/amazon/network_manager.rb, app/models/manageiq/providers/amazon/storage_manager/ebs.rb
These were missed in 09bb600991f39c1f6341c5e2fa09fdb0745246d8
=> Remove the require_nested calls for removed refresh workers

app/models/manageiq/providers/amazon/storage_manager/ebs.rb
This is a pluggable variant of https://github.com/ManageIQ/manageiq/pull/19799
=> Add nice display name for Amazon's EBS Manager

app/models/manageiq/providers/amazon/cloud_manager.rb
With this the form becomes semantically more correct...
=> Add type to the list of validation dependencies

app/models/manageiq/providers/amazon/cloud_manager.rb
Created analogously with `self.create_from_params`. Related API PR: https://github.com/ManageIQ/manageiq-api/pull/753
Parent issue: https://github.com/ManageIQ/manageiq/issues/18818
=> Implement a method that allows editing with incoming DDF params

spec/models/manageiq/providers/amazon/cloud_manager/orchestration_stack_spec.rb
This fixes a sporadic test failure:
https://travis-ci.org/ManageIQ/manageiq-providers-amazon/jobs/654921078#L1912
=> Fix an uninitialized constant Aws::CloudFormation

app/models/manageiq/providers/amazon/cloud_manager.rb, app/models/manageiq/providers/amazon/network_manager.rb, app/models/manageiq/providers/amazon/storage_manager/ebs.rb, app/models/manageiq/providers/amazon/storage_manager/s3.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb, spec/models/manageiq/providers/amazon/aws_refresher_spec_counts.rb, spec/models/manageiq/providers/amazon/cloud_manager/stubbed_refresher_spec.rb, spec/models/manageiq/providers/amazon/cloud_manager/vcr_specs/targeted_refresh_scope_spec.rb
just what it says on the tin
@miq-bot add_label cleanup
=> remove inventory object refresh

app/models/manageiq/providers/amazon/cloud_manager.rb, spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
Cross Repo Tests: https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/106
Core PR: https://github.com/ManageIQ/manageiq/pull/20039
=> Make Provider Catalog Types Pluggable

CHANGELOG.md
=> Updates for Sprint 133

app/models/manageiq/providers/amazon/cloud_manager/vm/operations.rb, spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
Needed for: https://github.com/ManageIQ/manageiq/pull/20222
=> Add supports terminate feature

db/fixtures/aws_regions.yml
=> Add the EU South Milan Region

app/models/manageiq/providers/amazon/cloud_manager/refresh_worker.rb, spec/models/manageiq/providers/amazon/cloud_manager/refresh_worker_spec.rb
Depends on: https://github.com/ManageIQ/manageiq/pull/20302
=> Move combined refresh workers to core

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb, app/models/manageiq/providers/amazon/inventory/persister/definitions/cloud_collections.rb
Depends on: https://github.com/ManageIQ/manageiq/pull/20396
=> Rename the key_pairs collection

app/models/manageiq/providers/amazon/cloud_manager.rb
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277
=> Update DDF schema to version 2

app/models/manageiq/providers/amazon/cloud_manager.rb, spec/models/manageiq/providers/amazon/cloud_manager_spec.rb
While technically the providers are static, they can be prevented or exposed via Settings.  Since we were memoizing a dynamic value, subsequent changes were not reflected.
=> Fix bug where new regions are not reflected in the list

.codeclimate.yml, .gitignore, .rubocop.yml, .rubocop_cc.yml, .travis.yml, .yamllint, README.md, Rakefile, bin/ci/after_script, lib/manageiq/providers/amazon/engine.rb, lib/tasks/README.md, lib/tasks_private/spec.rake, manageiq-providers-amazon.gemspec, spec/spec_helper.rb
=> Plugin Generator Updates

app/models/manageiq/providers/amazon/inventory/persister.rb
=> Use the tag_mapper from the core Persister

spec/models/manageiq/providers/amazon/aws_refresher_spec_common.rb
Use hash_including() so that new fields don't cause the tests to fail
=> Fix the service_instance#extra matcher

.codeclimate.yml, .rubocop.yml, .rubocop_cc.yml, manageiq-providers-amazon.gemspec
Depends on: https://github.com/ManageIQ/miq_bot/pull/506
=> Switch to manageiq-style

app/models/manageiq/providers/amazon/cloud_manager.rb
Depends on https://github.com/ManageIQ/manageiq/pull/20775
@miq-bot add_label enhancement, kasparov/no
=> Set the supports :auth_key_pair_create on the EMS

lib/manageiq/providers/amazon/engine.rb
Part of https://github.com/ManageIQ/manageiq/pull/20950
@agrare Please review.
=> Move logger initialization and configuration into plugins

app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb, spec/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume_spec.rb
Required for https://github.com/ManageIQ/manageiq-ui-classic/pull/7399
=> Fixed the creation of CloudVolumes via API/DDF

app/models/manageiq/providers/amazon/container_manager/refresh_worker.rb, app/models/manageiq/providers/amazon/container_manager/refresh_worker/watch_thread.rb, app/models/manageiq/providers/amazon/inventory/collector/container_manager.rb, app/models/manageiq/providers/amazon/inventory/collector/container_manager/watch_notice.rb, app/models/manageiq/providers/amazon/inventory/parser/container_manager.rb, app/models/manageiq/providers/amazon/inventory/parser/container_manager/watch_notice.rb, app/models/manageiq/providers/amazon/inventory/persister/container_manager.rb, app/models/manageiq/providers/amazon/inventory/persister/container_manager/watch_notice.rb, config/settings.yml
=> Add WatchNotice subclasses and enable streaming refresh

app/models/manageiq/providers/amazon/agent_coordinator_worker.rb, spec/models/manageiq/providers/amazon/agent_coordinator_worker_spec.rb
The AgentCoordinatorWorker runs 1 copy if there are any valid amazon providers in the zone and the smartproxy role is enabled.
It was pretending to be a PerEmsWorker and overriding the desired_queue_names method but didn't override the instance queue_name so sync_workers was constantly getting:
```
ManageIQ::Providers::Amazon::AgentCoordinatorWorker.sync_workers Workers are being synchronized: Current: [\"ems_0\"], Desired: [\"ems_agent_coordinator\"]"
```
Instead of trying to be a PerEmsWorker simply make it a standard worker that checks for any valid EMSs before saying it has the required_role.
=> Fix AgentCoordinatorWorker sync_workers

app/models/manageiq/providers/amazon/agent_coordinator_worker.rb
Follow-up to #686 to make use of https://github.com/ManageIQ/manageiq/pull/21060
=> Refactor AgentCoordinatorWorker to use ProviderWorkerMixin

app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
https://github.com/ManageIQ/manageiq/pull/21181
=> Add CloudVolume supports update

app/models/manageiq/providers/amazon/inventory/parser/cloud_manager.rb
Fixes https://github.com/ManageIQ/manageiq-providers-amazon/issues/699
=> Don't normalize_os_name if image_location is nil

app/models/manageiq/providers/amazon/cloud_manager.rb
https://github.com/ManageIQ/manageiq/pull/21224
=> Add supports :metrics to Amazon CloudManager

app/models/manageiq/providers/amazon/inventory/persister/target_collection.rb
https://github.com/ManageIQ/manageiq/pull/21225
=> Use targeted persister strategy from core

app/models/manageiq/providers/amazon/storage_manager/ebs.rb, app/models/manageiq/providers/amazon/storage_manager/s3.rb
=> Move to Block/ObjectStorageManager for EBS/S3

app/models/manageiq/providers/amazon/cloud_manager/vm/operations/power.rb
Goes with https://github.com/ManageIQ/manageiq/pull/21278
=> Convert Vm#validate_pause to SupportsFeatureMixin

systemd/manageiq-providers-amazon_agent_coordinator@.service, systemd/manageiq-providers-amazon_cloud_manager_event_catcher@.service, systemd/manageiq-providers-amazon_cloud_manager_metrics_collector@.service, systemd/manageiq-providers-amazon_cloud_manager_refresh@.service, systemd/manageiq-providers-amazon_container_manager_event_catcher@.service, systemd/manageiq-providers-amazon_container_manager_refresh@.service, systemd/manageiq-providers-amazon_storage_manager_s3_refresh@.service
part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)
=> add properties files to systemd

systemd/manageiq-providers-amazon_agent_coordinator@.service, systemd/manageiq-providers-amazon_cloud_manager_event_catcher@.service, systemd/manageiq-providers-amazon_cloud_manager_metrics_collector@.service, systemd/manageiq-providers-amazon_cloud_manager_refresh@.service, systemd/manageiq-providers-amazon_container_manager_event_catcher@.service, systemd/manageiq-providers-amazon_container_manager_refresh@.service, systemd/manageiq-providers-amazon_storage_manager_s3_refresh@.service
=> run service as manageiq user

app/models/manageiq/providers/amazon/container_manager/refresh_worker/watch_thread.rb
=> Move endpoint notice filtering into base class

lib/tasks_private/release.rake
=> Add branch release tasks

app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Part of https://github.com/ManageIQ/manageiq/pull/21393
=> Convert cloud volume operations to SupportsFeatureMixin

app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Goes with https://github.com/ManageIQ/manageiq/pull/21457
=> Convert AuthKey operations to SupportsFeatureMixin

app/models/manageiq/providers/amazon/cloud_manager.rb, app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Required for:
* https://github.com/ManageIQ/manageiq-api/pull/1098
=> Replace auth_key_pair_create with create

app/models/manageiq/providers/amazon/inventory/collector/target_collection.rb
=> Move add_target! and references to core collector

app/models/manageiq/providers/amazon/cloud_manager.rb, app/models/manageiq/providers/amazon/container_manager.rb, app/models/manageiq/providers/amazon/network_manager.rb, spec/models/manageiq/providers/amazon/network_manager_spec.rb
part of ManageIQ/manageiq#21573
=> renaming supports :ems_network_new to update

app/models/manageiq/providers/amazon/container_manager.rb, app/models/manageiq/providers/amazon/container_manager/container_template.rb, app/models/manageiq/providers/amazon/container_manager/service_instance.rb, app/models/manageiq/providers/amazon/container_manager/service_offering.rb, app/models/manageiq/providers/amazon/container_manager/service_parameters_set.rb
Required for https://github.com/ManageIQ/manageiq/pull/21597
=> Fix missing AKS subclasses

app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
Fixed the missing fields in the add form and fixed the edit form so it properly loads.
Before:
After:
@miq-bot add-label bug
=> Fixed the cloud volume add/edit form

app/models/manageiq/providers/amazon/cloud_manager/auth_key_pair.rb
Merge together with: https://github.com/ManageIQ/manageiq/pull/21759
=> Refactor AuthKeyPair.raw_create_key_pair

app/models/manageiq/providers/amazon/storage_manager/s3.rb, app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
Adds support for creating cloud object store containers.
Co-depends:
* https://github.com/ManageIQ/manageiq/pull/21791
=> Add support for creating cloud object store containers

app/models/manageiq/providers/amazon/storage_manager/s3/cloud_object_store_container.rb
part of: https://github.com/ManageIQ/manageiq-api/pull/1142
Moved fields to provider repo for the create cloud object store container form as well as add support for creating cloud object store container form.
Fields:
=> Added fields for create cloud object store container form and support for create

app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb, spec/factories/cloud_database.rb, spec/models/manageiq/providers/amazon/cloud_manager/cloud_database_spec.rb
- https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/Client.html#create_db_instance-instance_method
@miq-bot assign @agrare, @GilbertCherrie
=> Create cloud databases support

app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb, spec/models/manageiq/providers/amazon/cloud_manager/cloud_database_spec.rb
- https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/RDS/Client.html#delete_db_instance-instance_method
=> Delete cloud database support

app/models/manageiq/providers/amazon/storage_manager/ebs/cloud_volume.rb
part of https://github.com/ManageIQ/manageiq/pull/21841
=> rename CloudVolume#attach_volume to attach

app/models/manageiq/providers/amazon/cloud_manager.rb
Follow-up to: https://github.com/ManageIQ/manageiq/pull/21542
cc @kbrock
=> Cleanup duplicated supports_authentication? methods

.github/workflows/instance_types.yaml
* Change back to running weekly now that we have solved the permissions issue
* Set the committer/author to miq-bot to prevent unverified commits from the author of the most-recent master commit
* Set the enhancement label on PRs created
=> Change update_instance_types committer/author

app/models/manageiq/providers/amazon/cloud_manager/cloud_database.rb
Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/8339
@miq-bot add-reviewer @nasark 
@miq-bot add-reviewer @kbrock 
@miq-bot assign @kbrock
=> Adding validator for required fields

spec/models/manageiq/providers/amazon/cloud_manager/vm_spec.rb
part of https://github.com/ManageIQ/manageiq/issues/21179
=> rename Vm Operation context

.github/workflows/ci.yaml, .github/workflows/instance_types.yaml
Upgrade workflows to actions/checkout@v3
=> Upgrade workflows to actions/checkout@v3

.github/workflows/ci.yaml, .github/workflows/instance_types.yaml
Update GitHub Actions versions
=> Update GitHub Actions versions

.github/workflows/ci.yaml, .github/workflows/instance_types.yaml
Update actions/checkout version to v4
=> Update actions/checkout version to v4

spec/models/manageiq/providers/amazon/container_manager_spec.rb
https://github.com/ManageIQ/manageiq/pull/22716
=> Add ContainerManager #pause! and #resume! specs

config/regions.yml, lib/tasks_private/regions.rake, spec/models/manageiq/providers/amazon/regions_spec.rb, spec/vcr_cassettes/manageiq/providers/amazon/regions.yml
Update the list of aws regions with the rake aws:extract:regions utility
Fixes ManageIQ/manageiq#22744
=> Update AWS regions.yml

.github/workflows/instance_types.yaml
=> Update GHA versions
